### ISSUE TITLE
'appendChild' of null in scrollbarSize.js:18

### ISSUE THREAD

**Issue by winterblack** [clauderic/react-infinite-calendar#100]
I get this error when I run your example code:

```
scrollbarSize.js:18 Uncaught TypeError: Cannot read property 'appendChild' of null
    at exports.default (scrollbarSize.js:18)
    at Object.<anonymous> (index.js:138)
    at __webpack_require__ (bootstrap 1891148…:19)
    at Object.<anonymous> (bundle.js:5069)
    at Object.exports.__esModule (bundle.js:5561)
    at __webpack_require__ (bootstrap 1891148…:19)
    at Object.<anonymous> (index.js:3)
    at __webpack_require__ (bootstrap 1891148…:19)
    at Object.<anonymous> (entry.jsx:3)
    at __webpack_require__ (bootstrap 1891148…:19)
﻿

​
```

## Steps to reproduce:

1. `npm install babel-core babel-loader babel-preset-es2015 babel-preset-react css-loader react react-addons-css-transition-group react-dom react-infinite-calendar style-loader webpack --save`
2. create `webpack.config.js`
3. create `index.html` with `<div id='root'></div>`
4. `webpack`
5. copy paste example into `entry.jsx`
6. open `index.html`

**Comment by clauderic** [comment]
This is the line that's causing an error:
https://github.com/react-bootstrap/dom-helpers/blob/master/src/util/scrollbarSize.js#L16

The only scenario where `document.body` would be undefined is if you're trying to access it before it's declared (i.e., if your script is in the `<head>` of the page).

Either place your script at the end of the `<body>` tag or defer the javascript from being initialized until the document is ready.

**Comment by micahalcorn** [comment]
@winterblack did you figure out what the issue was on this?

@clauderic I'm running into the same problem simply by adding the import statement. Should I have to worry about whether the document is ready just to import a library? I'm using [react_on_rails](https://github.com/shakacode/react_on_rails).

**Comment by clauderic** [comment]
@micahalcorn It has to do with where your `<script>` tag that imports the bundled javascript file of your application is located in the `document`. Make sure it comes after your `<body>` tag, or, failing that, make sure you don't call `ReactDOM.render` until the [document is ready](https://developer.mozilla.org/en/docs/Web/Events/DOMContentLoaded).

**Comment by dben89x** [comment]
@micahalcorn @clauderic  I'm having the same problem, and am also using React on Rails. I'm not using a `script` tag anywhere. Does this need a `script` tag on an application level HTML file? I'm just simply trying to use `import InfiniteCalendar from 'react-infinite-calendar'` within my jsx file.

**Comment by micahalcorn** [comment]
@dben89x yes, @clauderic is correct that you can solve the problem by moving your `<%= javascript_include_tag 'application' %>` out of the `<head>` and into the end of the `<body>`, although I'm not clear on why `react_on_rails` is not handling this sort of thing. You can see a similar discussion [here on the `react-big-calendar` repo](https://github.com/intljusticemission/react-big-calendar/issues/283).
