### ISSUE TITLE
how to use react-infinite-calendar-events,it's not work  after import

### ISSUE THREAD

**Issue by lxfire** [clauderic/react-infinite-calendar#102]
hi,this calendar is so good ,I need selected callback event,just like beforeSelect、afterSelect,so i import react-infinite-calendar-events,but it's not work . I don't  know what should i do,can u give me some idea?
tks

**Comment by clauderic** [comment]
The `beforeSelect` and `afterSelect` callbacks were removed in version `2.0.0`, you can import the controlled version of react-infinite-calendar directly by importing `import {Calendar} from 'react-infinite-calendar'` instead, which should give you enough control to decide whether to update the state of your application on select or not.
