### ISSUE TITLE
react-inifinite-calendar not working in IE11

### ISSUE THREAD

**Issue by mitchellcunha** [clauderic/react-infinite-calendar#103]
I was trying to see if this component would work for an implementation I am contributing to, but realized that it has an issue rendering in IE11 (and IE10). I checked the demo site for this component and realized that was broken in IE11 as well. Here is there error I encountered:

`SCRIPT5007: Unable to get property '__reactInternalInstance$he17twt1w9hj' of undefined or null reference`

Any idea if this may be fixed in the future?

**Comment by almoraleslopez** [comment]
Hi. Tested in IE11 and it's working.

Versions:
"react-infinite-calendar": "^2.2.0"
"date-fns": "^1.28.4"
"react-addons-css-transition-group": "^15.5.2"

**Comment by clauderic** [comment]
Hey @mitchellcunha, thanks for pointing out this issue. This is just an issue with the demo site, forgot to include `babel-polyfill`. IE10 and IE11 don't support certain features such as `Object.assign`, but you can easily solve this in your application by polyfilling them.

**Comment by mitchellcunha** [comment]
Thanks for looking into that, I appreciate it.
