### ISSUE TITLE
range header does not work in landscape mode

### ISSUE THREAD

**Issue by chrisdrackett** [clauderic/react-infinite-calendar#105]
screenshot of issue:

![example](https://d3vv6lp55qjaqc.cloudfront.net/items/46012J2o1y1R3d2r2M05/Screen%20Shot%202017-04-26%20at%201.21.26%20PM.png?X-CloudApp-Visitor-Id=2456&v=c2418703)

**Comment by clauderic** [comment]
The `withRange` HOC is experimental and does not currently support landscape mode. This isn't something I plan on working on in the near future, but PRs are welcome.
