### ISSUE TITLE
range indicator "breaks" as calendar get wider

### ISSUE THREAD

**Issue by chrisdrackett** [clauderic/react-infinite-calendar#106]
here is an example when in landscape mode:

![example](https://d3vv6lp55qjaqc.cloudfront.net/items/46012J2o1y1R3d2r2M05/Screen%20Shot%202017-04-26%20at%201.21.26%20PM.png?X-CloudApp-Visitor-Id=2456&v=c2418703)

**Comment by clauderic** [comment]
Fixed by e654e10, will go out in the next minor release.
