### ISSUE TITLE
styles start to have issues when used under 400px wide or so

### ISSUE THREAD

**Issue by chrisdrackett** [clauderic/react-infinite-calendar#107]
for example, selection circles get cut off, range header overflows:

![example](https://d3vv6lp55qjaqc.cloudfront.net/items/2P0K0946093M3Y363q3u/Screen%20Shot%202017-04-26%20at%201.31.14%20PM.png?X-CloudApp-Visitor-Id=2456&v=daa1ac33)

**Comment by clauderic** [comment]
The styles provided out of the box are a set of reasonable defaults. Feel free to override them if you need to support smaller sizes. If you come up with something that others could benefit from, PRs are welcome.
