### ISSUE TITLE
passing `false` to selected when using range says invalid in header

### ISSUE THREAD

**Issue by chrisdrackett** [clauderic/react-infinite-calendar#108]
![example](https://d3vv6lp55qjaqc.cloudfront.net/items/2V2A461F2y0n2x3q1r43/Screen%20Shot%202017-04-26%20at%201.35.32%20PM.png?X-CloudApp-Visitor-Id=2456&v=74e1d3e5)

**Comment by clauderic** [comment]
Fixed by 7ccacd2, will go out in the next minor release.
