### ISSUE TITLE
with a limited number of months, "year" view does not fill available area

### ISSUE THREAD

**Issue by chrisdrackett** [clauderic/react-infinite-calendar#109]
For example, in the following example I've made the last 14 months available. This consists of 4 rows of months (2 for each year) that should easily fit in the available area. That being said, the first row is hidden and there is a good deal of gray space around the scrolling section.

![example](https://d3vv6lp55qjaqc.cloudfront.net/items/2L2z2A1L292B3i1D3t10/Screen%20Shot%202017-04-26%20at%204.00.20%20PM.png?X-CloudApp-Visitor-Id=2456&v=77fc655a)

**Comment by clauderic** [comment]
Not sure which combination of props you used to get that result, I'm unable to replicate it myself. Happy to look into it if you can share the steps to reproduce.

You can also use the `displayOptions={{showMonthsForYears: false}}` in this scenario.
