### ISSUE TITLE
Updating scroll date when passing a function into `onselect`

### ISSUE THREAD

**Issue by dben89x** [clauderic/react-infinite-calendar#116]
I'm using the following code to update my component when a date is selected:
```
onSelect={date => {
  this.setState({fcDate: date})
}}
```
This properly updates the state to the selected date, but it does not update the selected date on the InfiniteCalendar component. Do I need to return something? Do I need to manually call `setScrollDate(date)` somehow?

**Comment by dben89x** [comment]
I eventually just went with the following to manually update the selected date:

```
<InfiniteCalendar
  selected={this.state.selectedDay}
  onSelect={date => {
    this.setState({fcDate: date}, () => {
      this.setState({selectedDay: date})
    })
}}
/>
```

And the component state:

```
const today = new Date()
this.state = {
  fcDate: today,
  selectedDay: today,
}
```

**Comment by clauderic** [comment]
I'm confused, why the duplication of state? Try this:

```
import {Calendar as InfiniteCalendar} from 'react-infinite-calendar';

<InfiniteCalendar
  selected={this.state.selectedDay}
  onSelect={date => {
    this.setState({selectedDay: date});
  }}
/>
```

**Comment by dben89x** [comment]
@clauderic I refactored that to one variable shortly after posting it. I'm simply a React newbie so I operate at about 25% efficiency of a normal competent dev :)

**Comment by clauderic** [comment]
Haha no worries! Glad you were able to figure it out 😄

**Comment by dben89x** [comment]
@clauderic Thank you for the amazing tool, by the way. I am loving it.
