### ISSUE TITLE
minimum height?

### ISSUE THREAD

**Issue by chrisdrackett** [clauderic/react-infinite-calendar#119]
I'm passing a height of `480` yet the calendar itself reprots as 627 high. Is there a minium height or am I doing something wrong? This is with `withRange` on.

**Comment by clauderic** [comment]
The `height` prop represents the height of the scrollable region, without taking the header into consideration. If you add in the height of the header, you'll get the same total.

**Comment by chrisdrackett** [comment]
what is the thinking behind this? I'm trying to fit the calendar into a popover, so it would be nice to set the total dimensions. For now I looked up the header height and subtracted it from the height I measure and need the calendar to fit in, but it would be nice not to need this step.
