### ISSUE TITLE
port to react native

### ISSUE THREAD

**Issue by mike623** [clauderic/react-infinite-calendar#12]
Great job man. I very interested that will you try to port to RN version?

**Comment by clauderic** [comment]
Hmm. Haven't given much thought to this yet, but I suppose I *could*. From what I've seen so far, the available calendar components for React Native aren't that great. If there's enough interest for this, I suppose I could consider it.

In the meantime though, you could look into bridging https://github.com/ruslanskorb/RSDayFlow, which is very similar to `react-infinite-calendar`

**Comment by vinceprofeta** [comment]
I would be totally down to help port this over to RN.

**Comment by kristojorg** [comment]
I'm interested!

**Comment by clauderic** [comment]
I've began experimenting a little to gage the level of effort that would be required to port to React Native. Within about an hour or two I was able to set up a basic ListView with the same look and feel as React Infinite Calendar, which I though was pretty fantastic. However, I've since hit a few roadblocks.

First off, if you try to set the initial `contentOffset` (which is a prop only supported on iOS, though I imagine you can use `ScrollView.scrollTo` on `componentDidMount` for Android) to the offset value for the current date, it takes an unreasonably long time to render. Second, trying to conditionally show/hide the overlay on scroll is also proving to be a performance bottleneck.

If you want to contribute or just poke around with it (be warned, it's still in it's early infancy so it doesn't look like much at the moment), go check out https://github.com/clauderic/react-native-infinite-calendar

**Comment by joshuapinter** [comment]
I would absolutely be willing to help port this over. Currently using [CalendarPicker](https://github.com/stephy/CalendarPicker/) and although Stephy has done a good job, the performance is weak and it isn't well maintained.

Just a heads up that you can limit the number of rows that a ListView pre-renders quite easily with the following props: 

> `initialListSize` number
> How many rows to render on initial component mount. Use this to make it so that the first screen worth of data appears at one time instead of over the course of multiple frames.
> 

> `pageSize` number
> Number of rows to render per event loop. Note: if your 'rows' are actually cells, i.e. they don't span the full width of your view (as in the ListViewGridLayoutExample), you should set the pageSize to be a multiple of the number of cells per row, otherwise you're likely to see gaps at the edge of the ListView as new pages are loaded.
> 

> `scrollRenderAheadDistance` number
> How early to start rendering rows before they come on screen, in pixels.
> 

I'll have a look at the repo when I get some free time as well.

**Comment by kristojorg** [comment]
@joshuapinter have you made any progress on this? I'm considering porting this for react native and I don't want to run into the issue that clauderic saw where you have to wait for everything to load even when using the `contentOffset` property. Did those props actually change the effect?

Thanks!

**Comment by joshuapinter** [comment]
@kristojorg Not yet, no. Keep me posted, though.

**Comment by clauderic** [comment]
@joshuapinter @kristojorg I don't believe any of those optimizations would help. I've tried all of them and AFAIK they don't solve the issue, that is, that ListView will still try to render every single row before the current month to reach the initial `contentOffset` value. 

I'm scratching my head trying to think of workarounds / different ways to approach the problem. If any react-native wizards stumble upon this and have a solution in mind, I'm all ears.

**Comment by kristojorg** [comment]
@clauderic the best approach I can think of is to manually virtualize a datablob just like ListView does and then to allow scrolling in either direction. 

I very briefly tried this and the problem I was seeing was that when you insert new items at the top of the underlying `ScrollView` everything gets pushed down. I am sure there is a way to keep the `ScrollView` positioned correctly, just haven't thought of it quite yet.

**Comment by kristojorg** [comment]
This exact same problem would actually solve a bunch of `ListView` related issues, like the ability to scroll to a row by id with dynamic height rows and the ability to load a `ListView` from bottom up (for a chat-like interface for example). 

Definitely something I'm considering working on in a few weeks. It's been a pain for me so far.

**Comment by clauderic** [comment]
I'm going to close this out for the time being. If you feel like contributing to this, jump over to https://github.com/clauderic/react-native-infinite-calendar and we can discuss there.
