### ISSUE TITLE
react-addons-css-transition-group is deprecated

### ISSUE THREAD

**Issue by syko** [clauderic/react-infinite-calendar#121]
Should use https://github.com/reactjs/react-transition-group instead.

From https://www.npmjs.com/package/react-addons-css-transition-group:
> In particular, its version 1.1.1 is a drop-in replacement for the last released version of react-addons-css-transition-group.

**Comment by clauderic** [comment]
Duplicate of #113. 

This was already addressed by 8873620, just update to the latest version to get the fix :)

**Comment by dashed** [comment]
fyi, `react-addons-css-transition-group` is still mentioned on the `README.md`

**Comment by snaerth** [comment]
You should update your README.md from **react-addons-css-transition-group** to **react-transition-group**
