### ISSUE TITLE
React Js Infinite calendar not working in IE

### ISSUE THREAD

**Issue by sandeep11jun** [clauderic/react-infinite-calendar#123]
Hi Guys,

Thanks for your great work and developing a great calendar.

This calander is not working in IE/IE-11 (Object.assign() doesn't work in IE). It would be good if you guys can work on this fix. I've implemented this plugin in my project but this is not working in IE.

Thanks in advance

**Comment by clauderic** [comment]
IE10 and IE11 don't support Object.assign, but you can easily solve this in your application by including a polyfill for it https://babeljs.io/docs/plugins/transform-object-assign/

**Comment by sandeep11jun** [comment]
Thanks for your quick response.

I'll do that and hope will get success.

thanks
