### ISSUE TITLE
Is it possible to use multiple dates and ranges in combination? Similar to this

### ISSUE THREAD

**Issue by TrustTheBoy** [clauderic/react-infinite-calendar#126]
![image](https://user-images.githubusercontent.com/20201085/27895691-10873550-6247-11e7-95ec-b21c8adea68b.png)

**Comment by clauderic** [comment]
Short answer: no.

Long answer: You can essentially build any functionality you want on top of `react-infinite-calendar` by using the exported `Calendar` primitive and creating your own higher-order-component that enhances the base component.

This is how all of the different variations work, see [withDateSelection](https://github.com/clauderic/react-infinite-calendar/blob/master/src/Calendar/withDateSelection.js), [withMultipleDates](https://github.com/clauderic/react-infinite-calendar/blob/master/src/Calendar/withMultipleDates.js), [withRange](https://github.com/clauderic/react-infinite-calendar/blob/master/src/Calendar/withRange.js).

If you come up with something that could be shared back with the rest of the community, feel free to send a PR to that effect.
