### ISSUE TITLE
Stylesheet not being imported

### ISSUE THREAD

**Issue by quachsimon** [clauderic/react-infinite-calendar#127]
I am trying to import the stylesheet as suggested in the README file but, it does not seem to be imported?

`import 'react-infinite-calendar/styles.css';`

I am using [react-starter-kit](https://github.com/kriasoft/react-starter-kit). 

I am thinking it has something to do with how webpack configures the css file? 

Any help would be great!

![screenshot 2017-07-08 21 31 16](https://user-images.githubusercontent.com/20729321/27990431-efead6d2-6424-11e7-91ef-51b3dbd31a63.png)

**Comment by NewbieX2** [comment]
Did you end up fixing this?  If so, how?
