### ISSUE TITLE
Range Selection do not show day on 2 dates selected

### ISSUE THREAD

**Issue by quachsimon** [clauderic/react-infinite-calendar#128]
In the [demo](http://clauderic.github.io/react-infinite-calendar/#/enhance-default-functionality/range-selection?_k=9xo5f6) when you select 1 date it displays the default locale `'ddd, MMM Do'` and when selecting a second date it shows `'MMM Do'` for the two. 

It doesn't seem to be the case for me though. 

If I don't set the `locale` prop it displays the default `'ddd, MMM Do'` regardless of whether 1 or 2 dates are selected and causes it to overlap.

How would I customize that display? 

I know I can adjust the width to be longer but, I want to stick with the default 400px and have it change accordingly.

![screenshot 2017-07-10 12 49 07](https://user-images.githubusercontent.com/20729321/28029493-3f7a09bc-656e-11e7-90c4-76b412c5182d.png)

**Comment by clauderic** [comment]
Unless you explicitly set the `locale.headerFormat` value, it will default to  `'MMM Do'` 
See https://github.com/clauderic/react-infinite-calendar/blob/master/src/Header/withRange.js#L15

This is a design constraint, there's really no way around this unless you reduce the font size.
