### ISSUE TITLE
Multi datepicker

### ISSUE THREAD

**Issue by SeanLF** [clauderic/react-infinite-calendar#13]
Would it be within the scope of this component to allow for the selection of one or more dates?

**Comment by clauderic** [comment]
You mean like a date range? If so, it's been discussed at length already in #4

**Comment by SeanLF** [comment]
No, I meant selecting multiple individual dates.

**Comment by clauderic** [comment]
Ah, I see. Possibly, though I'm not exactly sure how you would render that in the header. If you remove the header, then yes, it wouldn't be too difficult I suppose

**Comment by SeanLF** [comment]
What do you think about adding [carets](http://fontawesome.io/icon/caret-left/) or [chevrons](http://fontawesome.io/icon/chevron-left/) to navigate through the selected dates?

**Comment by clauderic** [comment]
Hmmm. I suppose that's not a horrible solution. I won't have time to tackle this for a couple of weeks, but I'll happily accept a PR. It should be fairly trivial to allow `selectedDate` to be an array, and from there it's simply a matter of tweaking the header

**Comment by SeanLF** [comment]
I'll see what I can do 👍

**Comment by Lakshman-LD** [comment]
Any updates on multi - date picker ?

**Comment by ncammarata** [comment]
Would also like multiple dates, and date ranges if possible. Would love love a status update if there is one!

**Comment by tommedema** [comment]
We also need this. If anyone created a fork that we can base our work on, we would very much appreciate it.

**Comment by vmaudgalya** [comment]
Any updates on the multi-date picker? Right now I'm "mocking" multiple selected dates using the disabledDates feature with custom styling, but this feature would be a lifesaver

**Comment by workingDog** [comment]
It would be really great to have the multi-date feature. Eagerly waiting for this. 
I'm using Bootstrap for this at the moment.

**Comment by davidpelayo** [comment]
Totally agree. We need this. I will try to do a PR soon.

**Comment by clauderic** [comment]
FYI, I'm currently working on this on #73 and this will ship with version 2.0

**Comment by lakshmantgld** [comment]
@clauderic Suresh has already implemmented this and we are using it in our production app. Give it a look: https://github.com/sureshmurali/react-infinite-calendar

This is how it looks in desktop:
![screen shot 2017-02-22 at 11 07 07](https://cloud.githubusercontent.com/assets/6481030/23194011/10f4c9d8-f8ef-11e6-9223-b2e29399be2a.png)

This is how it looks in mobile: 
![comingornot com- iphone 6](https://cloud.githubusercontent.com/assets/6481030/23194053/59fd80de-f8ef-11e6-9eb0-9d5818226a4b.png)

**Comment by clauderic** [comment]
That looks great @lakshmantgld! And thanks for the kind words, it's always awesome to hear what people have been doing with react-infinite-calendar 😄 

Version 2.0 is going to make it a lot easier to add functionality like multiple date selection, date ranges, displaying events, etc. without the need for creating your own fork. I'll also be providing some defaults out of the box for some of these. If you're curious to see what that looks like for multiple date selection, here's a sneek peek: https://twitter.com/clauderic_d/status/834580710568689664

All of this is built through composition, and will be achieved through opt-in higher-order components that you can add to get this extra functionality. Something along the lines of:

```jsx
import InfiniteCalendar, {withMultipleDates} from 'react-infinite-calendar';

const MultipleDateCalendar = withMultipleDates(InfiniteCalendar);
```

The idea is users will also be able to create their own higher-order components if their use-case doesn't fit in the scope of the project

**Comment by clauderic** [comment]
Hey guys! Progress update: I just published `react-infinite-calendar` Version 2.0, which comes with multiple date selection out of the box  🎉

Check out the updated demo site to play with it: http://clauderic.github.io/react-infinite-calendar/#/enhance-default-functionality/multiple-date-selection

*Disclaimer: It's still experimental, but PRs are welcome to make it better!*

Here's the final look & feel I settled on:

<img width="448" alt="1953c030-f867-11e6-8a47-400c118f348a" src="https://cloud.githubusercontent.com/assets/1416436/23327917/40ae5766-fae3-11e6-853e-ee4e98d52b9c.png">

Usage is as follows:

```jsx
import InfiniteCalendar, {
  Calendar,
  defaultMultipleDateInterpolation,
  withMultipleDates,
} from 'react-infinite-calendar';

<InfiniteCalendar
  Component={withMultipleDates(Calendar)}
  interpolateSelection={defaultMultipleDateInterpolation}
  selected={[new Date(2017, 1, 10), new Date(2017, 1, 18), new Date()]}
/>
```

If you're curious about the implementation, check out https://github.com/clauderic/react-infinite-calendar/blob/master/src/Calendar/withMultipleDates.js

Thanks everyone for your patience!

**Comment by hasnainshafqatmlt** [comment]
@clauderic cool work 👍 
i have once question.
can we disable select unselect on click, and it only select those dates which i put in 'selected' ?

**Comment by ShavidzeT** [comment]
Nice work guys, datepicker works great.
Need multiple datepickers to get same ui <img src="http://www.picz.ge/img/s2/1708/12/d/d11198a7f57b.png" />
