### ISSUE TITLE
Unexpected token when import css 

### ISSUE THREAD

**Issue by tcm2029** [clauderic/react-infinite-calendar#130]
I followed the guideline from the readme page and added the following line in my js file (It's a react component)

import "react-infinite-calendar/styles.css";

But I encounter this error when running gulp:

events.js:160
      throw er; // Unhandled 'error' event
      ^
SyntaxError: Unexpected token

Does anyone know to fix it? Because I'm quite new to React

**Comment by clauderic** [comment]
You need to use the appropriate loader.

Assuming you're using [webpack](https://webpack.github.io/), check out https://github.com/webpack-contrib/css-loader
