### ISSUE TITLE
onSelect bugs on mobile browser

### ISSUE THREAD

**Issue by adrianha** [clauderic/react-infinite-calendar#134]
Hi, I'm facing an issue on mobile browser (Tested on Safari iOS & Chrome Android). It looks like theres another layer when select date on safari, so when i tap on new date and also theres obvious delay on chrome for android. Could you check this issue please?

Here's the repo example: https://github.com/adrianha/reactInfiniteCalendarTest
Thanks

**Comment by clauderic** [comment]
You'll likely want to enable [FastClick](https://github.com/ftlabs/fastclick) in your app.
