### ISSUE TITLE
not support IE9

### ISSUE THREAD

**Issue by YutHelloWorld** [clauderic/react-infinite-calendar#136]
Hey! I found the calendar use flex-box for layout .It's not support IE9. Is any solution?

**Comment by langri-sha** [comment]
All versions of IE prior to IE11 and IE Edge are effectively deprecated by the vendor since  January 12, 2016. The solution is to warn your users that they need to immediately upgrade their clients.

**Comment by clauderic** [comment]
You could try to re-write the css yourself, but this isn't something that I ever plan on fixing. As mentioned by @langri-sha, all browsers prior to IE11 are effectively deprecated, so best of luck if you're still trying to support them.
