### ISSUE TITLE
view mode

### ISSUE THREAD

**Issue by enniel** [clauderic/react-infinite-calendar#138]
How to only view dates?

**Comment by jsj14** [comment]
Is there a way to display the calendar on click of the input field and close it after the user is done selecting, because the color scheme and ui need not be necessarily suitable for every app?

**Comment by clauderic** [comment]
@enniel 
Yes, you can `import {Calendar} from 'react-infinite-calendar'` to achieve this.

`Calendar` is a controlled component (as opposed to uncontrolled, see https://reactjs.org/docs/glossary.html#controlled-vs-uncontrolled-components), therefore if you don't pass it an `onSelect` handler the selection will not update.

```js
import {Calendar} from 'react-infinite-calendar';
import {withDefaultProps} from 'react-infinite-calendar/lib/Calendar';

const ReadOnlyCalendar = withDefaultProps(Calendar);

export default function App () {
  const selectedDate = new Date();
  
  return (
    <ReadOnlyCalendar 
      selected={selectedDate}
      scrollDate={selectedDate}
     /> 
  );
}
```

If you'd like to disable the hover styles, you can probably overwrite them using `pointer-events: none` in CSS:

```css
.Cal__Day__root {
  pointer-events: none;
}
```

Here's a working example: 
https://www.webpackbin.com/bins/-KybLE1d-dokHJ3KFOQ_

**Comment by clauderic** [comment]
@jsj14 Something like this should do:

```js
class CalendarToggle extends React.Component {
  state = {
    visible: false,
  };

  toggleVisibility() {
    this.setState({
      visible: !this.state.visible,
    });
  }

  render() {
    return (
      <div>
        <button onClick={this.toggleVisibility.bind(this)}>Show/hide calendar</button>
        <div style={{display: this.state.visible ? 'block': 'none'}}>
          <InfiniteCalendar />
        </div>
      </div>
    )
  }
}
```

**Comment by jsj14** [comment]
Thanks @clauderic. I did do something like this eventually. Just wanted to know if the library had any plans of adding a close button at the top right corner or so...
