### ISSUE TITLE
Can't translate monthsShort

### ISSUE THREAD

**Issue by Niels-P** [clauderic/react-infinite-calendar#141]
Hi,

I try to translate months short, but it doesn't work. It stills shows the months in English, which of course isn't good.

`locale={{
                            name: 'dutch',
                            months: ["Januari","Februari","Maart","April","Mei","Juni","Juli","Augustus","September","Oktober","November","December"],
                            monthsShort: ["Januari","Februari","Maart","April","Mei","Juni","Juli","Augustus","September","Oktober","November","December"],
                            weekdays: ["Maandag","Dinsdag","Woensdag","Donderdag","Vrijdag","Zaterdag","Zondag"],
                            weekdaysShort: ["Ma","Di","Wo","Do","Vr","Za","Zo"],
                            todayLabel: {
                                long: 'Vandaag',
                                short: 'Van.'
                            },
                            week: {
                                dow: 1,
                                doy: 4
                            }
                        }}`

**Comment by clauderic** [comment]
Hey @Niels-P, as of `react-infinite-calendar^2.0.0`, you need to install the appropriate `date-fns` locale for the language you want to support.

```jsx
<InfiniteCalendar locale={{locale: require('date-fns/locale/nl')}} />
```

**Comment by Jiiun** [comment]
@clauderic You are right! I have solved the month problem! Thanks~
