### ISSUE TITLE
scrollToDate when 'selected' prop is changed

### ISSUE THREAD

**Issue by tonymckendry** [clauderic/react-infinite-calendar#142]
I've been rooting around in the source code trying to figure out how to accomplish this but so far am coming up empty. 

I want to be able to pass a date into the 'selected' prop and have the calendar scroll to that date automatically - is there currently a way to do this? If not, could you point me at where I might start? I

**Comment by clauderic** [comment]
This should already be the default behaviour, you can use the `scrollDate` prop if you would like to manually control which date the calendar scrolls to.

**Comment by barberdt** [comment]
@clauderic, on latest version (v2.3.1) and am not seeing this behavior working. Have tried to use the `scrollDate` prop as suggested in addition to the `selected` prop, but my calendar remains static without scrolling when the prop changes. Could I be missing something here?

Thanks!

**Comment by flieks** [comment]
I am having the same issue, its not scrolling with scrollDate
