### ISSUE TITLE
Support easy re-ordering of day columns

### ISSUE THREAD

**Issue by Shirikatsu** [clauderic/react-infinite-calendar#143]
Calendar shows day columns from left to right as Sunday - Saturday.

It would be nice to be able to change this so that we can set any day as the far left column and cascades to the right.

I.e. Instead of the default:
![screen shot 2017-09-22 at 16 39 05](https://user-images.githubusercontent.com/4716816/30752578-9be60266-9fb4-11e7-8f92-47363e696403.png)

Change to:
![screen shot 2017-09-22 at 16 41 03](https://user-images.githubusercontent.com/4716816/30752646-d87b6892-9fb4-11e7-9bce-3e1b4c722e8b.png)

**Comment by clauderic** [comment]
This is already something that's currently possible, see http://clauderic.github.io/react-infinite-calendar/#/internationalization/first-day-of-the-week

```js
<InfiniteCalendar locale={{weekStartsOn: 1}} />
```

**Comment by Shirikatsu** [comment]
Thanks and apologies for this redundant issue.
