### ISSUE TITLE
Custom placeholder when initial date is blank

### ISSUE THREAD

**Issue by iamsaksham** [clauderic/react-infinite-calendar#144]
As per [this](http://clauderic.github.io/react-infinite-calendar/#/basic-settings/blank-initial-state?_k=pgywre) example, when we have initial selected day as blank, then there is a placeholder which says `select a date`.
Is there any way we can have our custom placeholder text?
Use case is that in case of range selection, it still says `select a date` but i'd like it to say `select start and end date`

<img width="407" alt="screen shot 2017-10-02 at 9 32 04 am" src="https://user-images.githubusercontent.com/13564312/31063892-d4a45114-a754-11e7-905e-e2294730a38b.png">

**Comment by clauderic** [comment]
Sure, just edit the locale prop:

https://github.com/clauderic/react-infinite-calendar/blob/master/src/utils/defaultLocale.js#L2

```js
<InfiniteCalendar locale={{blank: 'Custom text to display when date is blank'}} />
```

**Comment by iamsaksham** [comment]
Wow, that was quick. Thanks a lot @clauderic 
Anyways very nice and awesome repo

**Comment by clauderic** [comment]
Thanks 😄
