### ISSUE TITLE
is it possible to put events on header? 

### ISSUE THREAD

**Issue by DastanSE** [clauderic/react-infinite-calendar#146]
![screen shot 2017-10-13 at 11 12 04](https://user-images.githubusercontent.com/24663729/31528796-1a6c3150-af9b-11e7-90da-0a6c5def0936.png)

**Comment by DastanSE** [comment]
http://www.ctbcculture.org/   like here

**Comment by clauderic** [comment]
Yes, if you create a custom renderer for the header this should be easily achievable. See the implementations of https://github.com/clauderic/react-infinite-calendar/blob/master/src/Header/withMultipleDates.js and https://github.com/clauderic/react-infinite-calendar/blob/master/src/Calendar/withMultipleDates.js, you should easily be able to fork both of those into your project and customize them to add that kind of functionality.
