### ISSUE TITLE
Read only/view mode - is there a way to disable onClick event?

### ISSUE THREAD

**Issue by bodziowagh** [clauderic/react-infinite-calendar#147]
Is there a way to only display the calendar and selected date/dates defined in `selected` property of  the component? Im looking for a way to disable the `onClick` event to avoid changing the selection. Disabling specific dates or days of the week workaround isn't a good solution for me, because it removes the prior selection.

Possible duplicate: #138

**Comment by clauderic** [comment]
Yes, you can `import {Calendar} from 'react-infinite-calendar'` to achieve this.

`Calendar` is a controlled component (as opposed to uncontrolled, see https://reactjs.org/docs/glossary.html#controlled-vs-uncontrolled-components), therefore if you don't pass it an `onSelect` handler the selection will not update.

```js
import {Calendar} from 'react-infinite-calendar';
import {withDefaultProps} from 'react-infinite-calendar/lib/Calendar';

const ReadOnlyCalendar = withDefaultProps(Calendar);

export default function App () {
  const selectedDate = new Date();
  
  return (
    <ReadOnlyCalendar 
      selected={selectedDate}
      scrollDate={selectedDate}
     /> 
  );
}
```

If you'd like to disable the hover styles, you can probably overwrite them using `pointer-events: none` in CSS:

```css
.Cal__Day__root {
  pointer-events: none;
}
```

Here's a working example: 
https://www.webpackbin.com/bins/-KybLE1d-dokHJ3KFOQ_

**Comment by bodziowagh** [comment]
Thanks! I'll check it out.
