### ISSUE TITLE
onSelect prop called when range is selected, not hovering

### ISSUE THREAD

**Issue by adhesivewombat** [clauderic/react-infinite-calendar#151]
Currently when selecting the end date of a range, the onSelect prop gets called anytime the user hovers over a date.  This can cause a lot of unnecessary updates when using a store like redux to control the date range and cause the picker to lag. 

It would be nice if that was changed so that it was only called when the end date is actually selected.  Another prop could be added to handle the hover action.

**Comment by jsj14** [comment]
Are you setting 2 states in the onSelect(), besides the dates ?

**Comment by adhesivewombat** [comment]
Right now I'm just setting the date range state and thats it.  It doesn't really cause noticeable lag, but I would prefer to only change the state when the date is actually selected and have a different control for hovering.

**Comment by jsj14** [comment]
Yes. I was trying to hide the calendar onSelect of the 'end' date and ran into this issue, since onHover also changes 'end' date. Now as a workaround I have to create another close button. Do you have any other suggestions, to handle hide/show of this calendar?

**Comment by adhesivewombat** [comment]
Hmm, I'm not sure if there's a better way to do it than that right now.

**Comment by clauderic** [comment]
You get an `eventType` argument in the `onSelect` callback, see https://github.com/clauderic/react-infinite-calendar/blob/master/src/Calendar/withRange.js#L111

**Comment by adhesivewombat** [comment]
Perfect!  Thanks clauderic.

**Comment by adhesivewombat** [comment]
I might make a pull request to add that to the documentation.
