### ISSUE TITLE
Click events

### ISSUE THREAD

**Issue by marek-sed** [clauderic/react-infinite-calendar#16]
Click events have sort of strange names, it took me a while to realize what are they doing.
beforeSelect -> onClick, that stops event propagation
onSelect -> onSelect,
afterSelect -> onSelected.

Also when I define beforeSelect then onSelect and afterSelect will not be called. I think
this should be decided by user.

**Comment by offsky** [comment]
If you define beforeSelect then you need to return true from that function if you want the other events to be called. Otherwise the selection is canceled as described in the docs.

**Comment by marek-sed** [comment]
@offsky thx I must have missed that, 
expected it to behave same as js Event, which propagates by default.

**Comment by clauderic** [comment]
Going to close this one out as I don't really think this is an issue and the docs are clear.
