### ISSUE TITLE
Any event on the Day selection ?

### ISSUE THREAD

**Issue by Asthonishia** [clauderic/react-infinite-calendar#162]
Hi,

Just a litlle question. Is thete any event triggered on day selection ?
Just asking because actually i want to trigger close on day selection only.

Best regards.

**Comment by wxu-aa** [comment]
Try the  `event.eventType === 3`

**Comment by clauderic** [comment]
There's an `onSelect` prop you can use for that:

```js
<InfiniteCalendar onSelect={() => this.close()} />
```

**Comment by Asthonishia** [comment]
@clauderic : The problem is that the "onSelect" close the datepicker after the first select, not the final one. So you can choose a month, but not a day. I'm looking for a solution to close only after day selection.

**Comment by wxu-aa** [comment]
@Asthonishia Hey, have you tried to use the `event` parameters ? If the `event.eventType === 3`, then it means it is after day selection.

**Comment by Asthonishia** [comment]
@wxu-aa not yet but it's interresting. How do you use it exactly ? On a "if" when onSelect is triggered ?

**Comment by wxu-aa** [comment]
@Asthonishia It would looks like this,


```js

const handleDateSelect = (event: { eventType: number, start: Date, end: Date }) => {
        if (event.eventType === 3) {
            YOUR_METHOD(event.start, event.end);
        }
    };

const calendar = <InfiniteCalendar
            Component={withRange(Calendar)}
            width={420}
            height={350}
            minDate={minDate}
            maxDate={maxDate}
            selected={{
                start: currentStartDate,
                end: currentEndDate,
            }}
            onSelect={handleDateSelect}
        />


```
