### ISSUE TITLE
Scroll past max date

### ISSUE THREAD

**Issue by aaronryden** [clauderic/react-infinite-calendar#165]
Would it be possible to prevent scrolling past the maxDate?

**Comment by clauderic** [comment]
Yes:

<img width="924" alt="screen shot 2017-11-27 at 4 52 46 pm" src="https://user-images.githubusercontent.com/1416436/33291318-6bf208d0-d393-11e7-9019-ba7ad571d739.png">

Use the `max` prop for that.
