### ISSUE TITLE
Document for beforeSelect callback

### ISSUE THREAD

**Issue by zli-aa** [clauderic/react-infinite-calendar#167]
It says that `beforeSelect` is supported in the features section, but the callback is not documented in the property section. And the callback seems not working.

> Events and callbacks – beforeSelect, onSelect, onScroll, etc.

Could you please help update the document? Thanks.

**Comment by clauderic** [comment]
Sorry, `beforeSelect` was deprecated in version 2.0 as it is no longer needed, you can use the controlled version of `react-infinite-calendar` instead by importing
```js
import {Calendar} from 'react-infinite-calendar'
```

I'll need to update the docs to remove references to `beforeSelect`

**Comment by ferarnoled** [comment]
I want to prevent the user to select the date (just capture what date he clicked). I don't think there is a way to do that now, it looks like with beforeSelect you could do that.

**Comment by daverag** [comment]
@clauderic We are now 2019 and the docs haven't been updated.  I need to know how to prevent the selection of a date, how do I achieve the functionality of beforeSelect in newer versions?
