### ISSUE TITLE
Better way to get selected state for infinite calendar range

### ISSUE THREAD

**Issue by justinhessdev** [clauderic/react-infinite-calendar#169]
I am trying to submit the `selected` date range in a chat:
The only way I was able to grab the `selected` state of the `Calendar` was by using `ref` 

`ref={(ref) => { this.calendar = ref }}`

Then when the submit button is `clicked` I pass `this.calendar.state.selected` 
Is there a better way to get the selection?

Usually there is some sort of `target` or `value` I can use: 
Is there an option to do something like `e.target.value`

        handleDatePickerSubmit(date) {
            const start = moment(date.start).format('ll');
            const end = moment(date.end).format('ll');
            this.props.submit({ messageText: `${start} - ${end}`});
        }

        render() {
                const today = new Date();
                return (
                    <div>
                        <InfiniteCalendar
                          Component={withRange(Calendar)}
                          height={150}
                          minDate={today}
                          selected={{
                              start: today,
                              end: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 7),
                          }}
                          locale={{
                              headerFormat: 'MMM Do',
                          }}
                          ref={(ref) => { this.calendar = ref }}
                        />

                        <Button
                          className="button-submit"
                          onClick={() => this.handleDatePickerSubmit(this.calendar.state.selected)}
                          content="Submit"
                        />
                    </div>
                );
        }

**Comment by clauderic** [comment]
Use the `onSelect` prop to keep track of the selected date range in your app's state:

```jsx
<InfiniteCalendar onSelect={(selectedDates) => {
      this.setState({selectedDates});
   }}
/>
```

**Comment by justinhessdev** [comment]
Thanks for your really quick response:

I tried that previously but it does not work properly for me.

For Range I need to click twice: However when I click the first time - it makes the start and end the same day. There is no more range.

**Comment by justinhessdev** [comment]
I initialize date picker with a range:

<img width="432" alt="screen shot 2017-12-07 at 12 31 20 pm" src="https://user-images.githubusercontent.com/7797010/33729127-a985431a-db4a-11e7-9323-ae5ef1ecfa34.png">

Then when I click once it loses the range:

<img width="426" alt="screen shot 2017-12-07 at 12 33 20 pm" src="https://user-images.githubusercontent.com/7797010/33729190-df18a742-db4a-11e7-8865-d4c81ee1dcde.png">

**Comment by clauderic** [comment]
What happens when you move your mouse? Do you not see the same behaviour as on the demo? http://clauderic.github.io/react-infinite-calendar/#/enhance-default-functionality/

**Comment by justinhessdev** [comment]
That is the same. 
However I want range , not single date picker

**Comment by AlexCatch** [comment]
I'm also having this issue.

**Comment by acmitch** [comment]
Yep. This is a issue when using the range funtionality. For now instead of changing state I saved to class variables.
