### ISSUE TITLE
minimum date before 1980,0,1 and max date beyond 2050,11,31

### ISSUE THREAD

**Issue by sudeshim3** [clauderic/react-infinite-calendar#176]
How about people selecting there birth date before 1980. Is there any way to expand the limit. I am not able to set below the default date of 1980,0,1

**Comment by mofelee** [comment]
You can change those props
https://github.com/clauderic/react-infinite-calendar/blob/master/src/Calendar/index.js#L32-L35

**Comment by arrlancore** [comment]
You can set the `min` props, with the date that you expected.
