### ISSUE TITLE
CSS is not properly displaying

### ISSUE THREAD

**Issue by NewbieX2** [clauderic/react-infinite-calendar#180]
Even with the most basic usage:

```
import InfiniteCalendar from 'react-infinite-calendar';
import 'react-infinite-calendar/styles.css';

ReactDOM.render(
  <AppContainer>
    <InfiniteCalendar />
  </AppContainer>,
  rootEl);
```

This is the result:

![image](https://user-images.githubusercontent.com/26860300/35577841-710b61d2-05b0-11e8-9a6a-bc62f7880cd4.png)

Is there something else I need to be doing?  I've checked previous closed issues, but there don't seem to be any solutions.  I'm using my project with create-react-app, if that is pertinent.

**Comment by NewbieX2** [comment]
Someone from my team seemed to fix the problem.  In the webpack configs, they changed instances of `include: paths.appStyles` to `include: paths.globalStyles`.

**Comment by rsong003** [comment]
@NewbieX2 I'm running into a similar issue can you post your webpack config?
