### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by stereobooster** [clauderic/react-infinite-calendar#187]
Hi @clauderic. Thank you for this project.

Can you please tell what is the status of the project. Do you need any help on it? Maybe you are looking for maintainers?

**Comment by MathiasKandelborg** [comment]
I wrote him an email a while ago asking about this project. He hasn't answered yet and I'm getting quite impatient 

If he still doesn't answer after a while, would anyone be interested in helping maintain a similar calendar based on/forked from this codebase? My thoughts being that this project is way too good to just die.

There are already quite a few PRs that would help get the project up to date and I'm willing to spend some time on issues and testing.

**Comment by Kaishiyoku** [comment]
@MathiasKandelborg The calendar component is currently being used by their own App for NirvanaHQ (https://nirvanahq.com) so I doubt that they will just abandon the repo. Anyway 
it has become quite quiet.

**Comment by MathiasKandelborg** [comment]
Oh, I hadn't seen that anywhere. I'll just go ahead and develop on a fork then.

**Comment by stereobooster** [comment]
Ok, I guess you do not have time at the moment. I will close the issue for now. Thank you for the project
