### ISSUE TITLE
Does calendar withRange support localization? 

### ISSUE THREAD

**Issue by abbudao** [clauderic/react-infinite-calendar#192]
I'm trying to translate my calendar but the header information is not getting translated at all.
Your localization example works fine without `Component={CalendarWithRange}` though.
Minimal (not working) example:
```js
<InfiniteCalendar
  locale={{
    locale: require('date-fns/locale/fr'),
    headerFormat: 'dddd, D MMM',
    weekdays: ['Dim', 'Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
    blank: 'Aucune date selectionnee',
    todayLabel: {
      long: 'Aujourd\'hui',
      short: 'Auj.',
    },
  }}
  selected={{
    start: new Date(),
    end: new Date(),
  }}
  Component={CalendarWithRange}
/>
```
Am I missing something? Should the localization be done elsewhere?
(Ps: Thank you for your awesome work )

**Comment by RyunDoKim** [comment]
same issue here... Did you fix it?
