### ISSUE TITLE
Allow weeks to start on Monday

### ISSUE THREAD

**Issue by offsky** [clauderic/react-infinite-calendar#22]
Can we have a setting to allow the week to start on Monday instead of Sunday?  Monday is the first day of the week in much of the world.

http://www.timeanddate.com/calendar/days/

**Comment by clauderic** [comment]
There is :) http://clauderic.github.io/react-infinite-calendar/#/basic-settings/first-day-of-the-week

Example usage:
```html
<InfiniteCalendar
 locale={{
   week: {
      dow: 1,
      doy: 4
   }
 }}
/>
```

**Comment by offsky** [comment]
Doh!  I should have read the manual more carefully. Sorry

**Comment by thisconnect** [comment]
Shouldn't Monday be the default?

**Comment by clauderic** [comment]
I don't think there really is a right or wrong answer to that question.

Monday is the default value in the ISO standard, but Sunday is the default value for [Moment.js](http://momentjs.com/)'s default locale (`en`). It's also a common default value, lots of [other](http://fullcalendar.io/) [calendar](http://amsul.ca/pickadate.js/) widgets have selected it.
