### ISSUE TITLE
Is it possible to add Month text support in locale?

### ISSUE THREAD

**Issue by maximdx** [clauderic/react-infinite-calendar#228]
Now we can set weekdays texts by providing the locale object.
Is it possible to add Month text support in locale as we do in weekdays please?

**Comment by bart-lewandowski-conichi** [comment]
especially cause passing locale in locale object like on the website does not work

**Comment by qkreltms** [comment]
It seems you cannot provide month as below, but you can edit month texts what you want at date-fns/locale/{language}/build_format_locale
```ts
    locale?: {
        blank?: string;
        headerFormat?: string;
        todayLabel?: {
            long: string;
        };
        weekdays?: string[];
        weekStartsOn?: 0 | 1 | 2 | 3 | 4 | 5 | 6;
    };
```

**Comment by maximdx** [comment]
Good to know that. Thanks for the help!
