### ISSUE TITLE
Display issue in days or years panel on page load until scroll is initiated

### ISSUE THREAD

**Issue by Ruzo** [clauderic/react-infinite-calendar#23]
Kind of a newbie here but did not see this issue mentioned anywhere.

On page load and reload, when display="days",  the days' panel is blank or half-filled when the min date is more than a few months apart than the selectedDate (even in the basic configuration).
Same as when display="years" but the min and selectedDate need to be about 20 years apart.

The '.Grid__cell' divs seem to be pushed down past the ' .Grid__innerScrollContainer'.

When you start scrolling, it starts displaying from the min date. It seems like the display does not get positioned to the selectedDate. It also considers selectedDate="null" as the default date in this behavior.

Here are some screenshots:
![infinite_calendar_issue](https://cloud.githubusercontent.com/assets/1992115/16323216/0f9561ac-3977-11e6-9377-2942115884ba.png)
![infinite_calendar_issue_years](https://cloud.githubusercontent.com/assets/1992115/16323223/195d83d6-3977-11e6-9dc0-716e19c1cecc.png)

**Comment by clauderic** [comment]
At first sight, this appears to be a bug with scrollbars and newer versions of https://github.com/bvaughn/react-virtualized/, I'll follow-up when I know more / find a solution

**Comment by bvaughn** [comment]
@clauderic and I chatted about this in Gitter and a guard for this edge-case (`scrollTop` being set before CSS styles have loaded) has been added to react-virtualized `Grid`. This has been released via 7.11.5.

**Comment by bvaughn** [comment]
`npm i react-virtualized@7.11.5 --save` and try again?

**Comment by clauderic** [comment]
Just published `1.1.15` which is updated to use the latest version of `react-virtualized`

**Comment by Ruzo** [comment]
Sorry I missed the replies. Thanks for the fix. Works great.
