### ISSUE TITLE
Floating Today Helper not reliable

### ISSUE THREAD

**Issue by offsky** [clauderic/react-infinite-calendar#24]
Ive noticed some bugs with the floating today helper. My interpretation of the helper is that if "today" is not visible on the screen, then the helper appears.

1) If you scroll all the way to the top, it hides. I think it should stay visible.
2) When scrolling back in time, the helper does not appear until "today" is several weeks below the fold.
3) When scrolling forwards in time, the helper does not appear until "today" is several months above the fold.

I think it would be more convenient if the today helper was always visible if "today" was not visible.

For these screenshots, today is June 24th.

![screen shot 2016-06-24 at 11 57 28 am](https://cloud.githubusercontent.com/assets/1110926/16347736/336fcd4c-3a03-11e6-8ea6-57ef8e6a0cd5.png)
![screen shot 2016-06-24 at 11 59 54 am](https://cloud.githubusercontent.com/assets/1110926/16347737/339b63bc-3a03-11e6-8acb-175405825b26.png)

**Comment by clauderic** [comment]
Those cases were all conscious decisions.

1) It's hidden when `scrollTop == 0` so as to not cover the dates underneath it
2 & 3) I think it would be annoying from a UX perspective to immediately show the today helper the instant `today` is no longer visible. It was implemented this way so as to be a helpful, unobtrusive way to scroll back to the current date when the user might have reasonably lost context.

**Comment by offsky** [comment]
Ok on #1. In the case of 2&3, can we have the helper appear when "today" has been scrolled the same distance out of view?  Right now scrolling up is about 2 weeks and scrolling down is about 4 weeks. Two blank rows feels about right to me, 4 feels like too much.

**Comment by clauderic** [comment]
They definitely should be the same, I remember that being an issue and never got around to fixing it. How about a prop along the lines of `todayHelperOffset`?

**Comment by offsky** [comment]
I dont think we need a prop for this.  Too many props becomes overload.  Whatever you decide is fine but it would be nice if both directions were consistent.

**Comment by clauderic** [comment]
Just published `1.1.15` which addresses this and adds the `todayHelperRowOffset` prop if you wish to customize the number of rows to scroll past before it appears.

**Comment by offsky** [comment]
Thanks for working on this.  I think there may still be a bug. The Today helper is appearing for me even when today is still visible (see screenshot):
![screen shot 2016-06-29 at 11 17 20 am](https://cloud.githubusercontent.com/assets/1110926/16463628/74fb9566-3deb-11e6-8675-8105d202587e.png)

**Comment by offsky** [comment]
I belive this is the fix:
`} else if (scrollTop <= this.todayOffset - monthHeight - rowHeight * todayHelperRowOffset) {`

**Comment by offsky** [comment]
I think there was a regression on this with the new 2.1.1 branch.  When I scroll backwards in time, the today helper shows up when I have scrolled 2 weeks away.  When I scroll forwards in time, you have to go 6 weeks before it appears.
