### ISSUE TITLE
Numbered badges for particular days

### ISSUE THREAD

**Issue by offsky** [clauderic/react-infinite-calendar#26]
I needed small colored number badges to show up on particular days, so I built this for myself.  Id be happy to clean up my code and create a pull request if this was functionality that you wanted in your project.

![screen shot 2016-07-07 at 11 41 25 am](https://cloud.githubusercontent.com/assets/1110926/16665527/cbe334f8-4438-11e6-9852-eea598d30830.png)

**Comment by clauderic** [comment]
Yeah this looks promising, you can submit a PR for it and we'll discuss there 👍

**Comment by offsky** [comment]
I never created a pull request. Sorry. But you can check out our fork where this is incorporated.  
https://github.com/Toodledo/react-infinite-calendar

**Comment by shivavelingker** [comment]
@clauderic I've never done a PR before, but it should be fine for me to attempt one, right? `Contributing.md` says to check before creating a new feature.
