### ISSUE TITLE
2 Bugs on mobile that make it not usable 

### ISSUE THREAD

**Issue by joeblew99** [clauderic/react-infinite-calendar#27]
Take the example here:
http://clauderic.github.io/react-infinite-calendar/#/customization/landscape-layout?_k=2xr4cj

Load it on you mobile, and the problems are pretty clear:

1. is not responsive, in that it does not scale down at all. The right hand side of the cal is off the screen even

2. When you swipe the cal down, it sometimes will scroll the cal, but mayn times will cause the mobile page to refresh.

**Comment by ThomsCass** [comment]
On what mobile ? I use it on Android and got no problems it is not responsive so you have to fix the size.

**Comment by clauderic** [comment]
@joeblew99 I'm happy to help but you have to provide *details*... What device are you using? What browser?

Even so, I haven't spent much time optimizing all the demos for mobile, so it's possible that the issues you're referring to are only specific to the demo site. I'm using `react-infinite-calendar` in a Cordova app and it runs great for both iOS and Android on my end.

To make the calendar responsive, you can simply use something like [AutoSizer](https://github.com/bvaughn/react-virtualized/blob/master/docs/AutoSizer.md) or calculate the width yourself in javascript and listen to the `resize` event.

As for the issues you're seeing when swiping down, those are generally browser-specific issues with nested overflow-scrolling elements. A quick search on StackOverflow should help you fix those.
