### ISSUE TITLE
Doesn't render while using the UMD build

### ISSUE THREAD

**Issue by RahulDole** [clauderic/react-infinite-calendar#29]
I'm using the UMD build by just adding the single script react-infinite-calendar.js and then I'm using the example code on your page.
But it gives this React error (I'm using React version 0.15):
`React.createElement: type should not be null, undefined, boolean, or number.`

**Comment by clauderic** [comment]
I've updated the UMD documentation slightly. InfiniteCalendar is available on the `window` object as:
```js
var InfiniteCalendar = window.InfiniteCalendar.default;
```

See this [jsfiddle](https://jsfiddle.net/clauderic/4rhn03do/)

**Comment by RahulDole** [comment]
Oh great! Thanks for sharing that and updating the doc.

**Comment by RahulDole** [comment]
Great! I tried that and now it works :) Thanks a lot, amazing work! :)
