### ISSUE TITLE
year selection

### ISSUE THREAD

**Issue by thisconnect** [clauderic/react-infinite-calendar#3]
hi, I love your calendar. Is there any way to easily select a year? I.e. 1950

**Comment by clauderic** [comment]
Hey there, thanks for the kind words 😄 

As for year selection, not currently, though this is one of the upcoming features. I haven't quite settled on what the UI is going to look like, but I was thinking of something along the lines of what's suggested in the [Material Design Guidelines for date-pickers](https://www.google.com/design/spec/components/pickers.html#pickers-date-pickers).

If you click on the year in the header, the view on the right would come up:
![material date-picker](https://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0B3321sZLoP_HVWZOVkdRQlJEdDg/components_pickers_date1.png)

Any thoughts/suggestions?

**Comment by thisconnect** [comment]
Yes that looks pretty, would that be a scrollable list too?

**Comment by clauderic** [comment]
Yep. Scrollable all the way from the `min` year to `max` year. My only concern UI wise is that it's kind of hidden, you have to know to click on the year. Android users will probably be familiar with that paradigm though

**Comment by thisconnect** [comment]
Selecting the year to change it is ok. Birthdate is a good example, unless the person using the calendar is adding the date of her/his new born, it will always be a year far away in the past.

What do you think about an option to start with the year selector? This would make sense in cases where the year is expected to not be the current year, `pickYearFirst` or similar

**Comment by clauderic** [comment]
Still a bit of work to do to properly add tests to this and tweak keyboard support, but the core functionality of jumping to years has been implemented. Should release to `npm` within a day or two

<img width="477" alt="screen shot 2016-06-04 at 11 13 15 pm" src="https://cloud.githubusercontent.com/assets/1416436/15803408/01bc28d0-2aaa-11e6-8c67-c90a934e48ef.png">

I've added an orange line under the current year, to echo the current look & feel that's been applied to the current date; I've found it helps a lot when you're searching for the current year and it gives your eye a reference point.

**Comment by thisconnect** [comment]
Looks very pretty, what do you think about an `showYearFirst` option?
Additionally maybe `showYearOnly` if one needs just a year picker?

**Comment by clauderic** [comment]
I added a prop called `display` which can be set to either `years` or `days`, which effectively does the same thing as what you're describing. As for something like `showYearOnly`, I don't thinkg that's really a use case I'm willing to support.

**Comment by clauderic** [comment]
This has been released 🎉

**Comment by thisconnect** [comment]
Looks very pretty, thanks a lot!

Would it make sense to add an event onYearSelect or similar?

**Comment by clauderic** [comment]
Possibly. Though I can't really think of a use case that would be solved by simply listening to onDateSelect. Do you have a use case in mind?

**Comment by thisconnect** [comment]
Oh thanks yes that should be sufficient
