### ISSUE TITLE
why move the react-addons-css-transition-group and  react-addons-shallow-compare  Dependencies to  peerDependencies?

### ISSUE THREAD

**Issue by shikelong** [clauderic/react-infinite-calendar#30]
In npm v3. use `npm install` without arguments can't auto automatically install peerDependencies.

**Comment by masylum** [comment]
Same here

**Comment by clauderic** [comment]
This is by design, in order to avoid having version conflicts when using react-addons-* libraries and maintain compatibility with React 0.14, my understanding is that the library has to be a peerDependency.
