### ISSUE TITLE
Moment Dependency Concern

### ISSUE THREAD

**Issue by sandysaders** [clauderic/react-infinite-calendar#31]
I've been using this component in my application and we're getting ready to deploy. However as we have been optimizing the size of out application we began using webpack dependency graph to visualize what is taking up the most size in our application. Turns out it's `moment.js` which is coming from `react-infinite-calendar` is taking up 20% of the application size. Is there anyway you guys could some how remove this dependency or extrapolate the functionality that you are using out from moment.js? 

Not sure if `moment` offers but some modules like `lodash`, and `react-bootstrap` allow you to cherry pick the functionality you need from them in order to shed some size of your application.

please let me know.

**Comment by clauderic** [comment]
Unfortunately it appears not, check out https://github.com/moment/moment/issues/2373 for more info. Just a thought, and not sure whether this is an option for you, but if size is a concern you can perhaps try using [rollup](http://rollupjs.org/)

**Comment by sandysaders** [comment]
@clauderic I'm using webpack instead of rollup, It's just jarring that a 3rd party component is accountable for 20% or greater of the application I'm working on. It is also not really the component itself taking up the size but rather its dependencies. Given that our application Is extremely large this should give pause for concern. It is also quite noticeable as the page that we are dropping the component in takes a visibly noticeable longer time to load. Idk if you have tried to benchmark the component but maybe you should. People who want to use it like in our case will not be able to use it in production any longer just because of sheer size that cannot be justified. I think the component is really really great. Its sad we will not be able to use it.

**Comment by clauderic** [comment]
To be clear, I agree with you on all points stated above. Unfortunately I don't have the capacity to look into this at the moment, though I might someday given enough interest. If it's something you feel strongly about, I'd happily accept a PR to switch from `moment` to [date-fns](https://github.com/date-fns/date-fns)

**Comment by sandysaders** [comment]
Maybe https://github.com/react-component/calendar can give you an Idea of how to handle locale without moment. We're moving to this calendar with a smaller footprint for now.
