### ISSUE TITLE
[Request] Callback on arrow keyPress

### ISSUE THREAD

**Issue by bhsiung** [clauderic/react-infinite-calendar#34]
Hi there,
I've found a missing logic for keyboard support. Which is to have a callback every time user press arrow key and have the current date as param

thank you!

**Comment by clauderic** [comment]
This isn't something that's currently supported, though feel free to submit a PR. If the user uses the keyboard and selects a date, a callback *will* be fired when the date is selected.

**Comment by GregoryPotdevin** [comment]
Something like this works, but it changes the moment onKeyDown is called (it's called at the end of the handler instead of at the beginning). The main change is that in this case onKeyDown isn't called when Enter is pressed (though that could be added back in if needed).
