### ISSUE TITLE
Way to start from a date other than month start

### ISSUE THREAD

**Issue by execat** [clauderic/react-infinite-calendar#37]
Is there a way to start the calendar from a non-1st?
Like beginning of this week, for example?

**Comment by clauderic** [comment]
How do you mean? In terms of rendering, no. You can set the previous dates to be disabled however and specify a `minDate` to render

**Comment by execat** [comment]
@clauderic Yes, but the experience on using `minDate` especially in final few days of the calendar month might not be desirable for every use case because the calendar shows 75% of more of the dates grayed out with the final few dates clickable.

An example where this is desired is a planning app where you'd usually have to plan in the next one month and do not care about the past events.

**Comment by clauderic** [comment]
I see. I'm afraid that's not really a use case I'd be willing to support at the present time given the complexities it entails, though feel free to submit a PR if you feel strongly about it and I'll be happy to review it.
