### ISSUE TITLE
date range selection

### ISSUE THREAD

**Issue by capaj** [clauderic/react-infinite-calendar#4]
allow for selecting date range instead of 1 specific date

**Comment by clauderic** [comment]
When building this component out, I thought of working on that functionality. However, I felt that there already were a lot of other great date-pickers out there that supported this kind of functionality. 

Don't currently have plans to support this, but if you can make a case for why it should be supported, I'd be willing to consider it.

**Comment by bvaughn** [comment]
A single input to pick a date-range makes for very difficult UX. (My wife has spent a lot of time recently working on one for internal use at Google, and it's a huge hassle.) Our advice (for what it's worth, if anything) would be to just use 2 date pickers for the range and save yourself a lot of headache. :)

**Comment by clauderic** [comment]
@bvaughn That was kind of my take on this as well. Nevermind the fact that I feel like it's out of the scope of what this component aims to solve. Thanks for your advice, appreciate it

**Comment by wmertens** [comment]
I must say that I really like the datepicker that Ryanair uses https://www.ryanair.com/gb/en/ (pick a destination airport to see it). It shows two date input fields and automatically focuses on the next one when you pick a date

**Comment by syko** [comment]
Yeah, ryanair's datepicker is basically 2 range-pickers in sync with each other.
My "strong case" for it is that it's an awesome datepicker and it's lacking a function that we really need.

Would you be willing to accept a PR if we implemented range selection in a backwards-compatible manner?

**Comment by clauderic** [comment]
I'd happily accept a PR, so long as the UX is on fleek... :P

**Comment by syko** [comment]
I wouldn't have it any other way ;)

**Comment by offsky** [comment]
Could range selection be done via click and drag to select a range of dates? That doesn't seem to me like it would impact the current design much and could be disabled by default.

**Comment by wmertens** [comment]
I rather imagine it would work like
http://onefinestay.github.io/react-daterange-picker/ but with infinite
scrolling added… I don't think click and drag is very accurate?


On Wed, Jun 22, 2016 at 7:24 PM Jake Olefsky <notifications@github.com>
wrote:

> Could range selection be done via click and drag to select a range of
> dates? That doesn't seem to me like it would impact the current design much
> and could be disabled by default.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/clauderic/react-infinite-calendar/issues/4#issuecomment-227816225>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AADWlr2MGtEJT6RD44m9zv6TLku3NVdpks5qOW_OgaJpZM4IqBTp>
> .
>
-- 

Wout.
(typed on mobile, excuse terseness)

**Comment by offsky** [comment]
Here is a crude half-finished prototype of drag and drop date selection. 
https://github.com/Toodledo/react-infinite-calendar/tree/selectRange

I'm probably going to keep working on this.

**Comment by wmertens** [comment]
Nice! But how will that interact with touch scrolling? Long press to start
the drag?

On Wed, Jun 22, 2016 at 10:33 PM Jake Olefsky <notifications@github.com>
wrote:

> Here is a crude half-finished prototype of drag and drop date selection.
> https://github.com/Toodledo/react-infinite-calendar/tree/selectRange
>
> I'm probably going to keep working on this.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/clauderic/react-infinite-calendar/issues/4#issuecomment-227867776>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AADWlpP-Gp7OWn2nsN8OOldN-1BI-KAlks5qOZwAgaJpZM4IqBTp>
> .
>
-- 

Wout.
(typed on mobile, excuse terseness)

**Comment by offsky** [comment]
It probably won't do any drag select on touch since Im using "onMouse" instead of "onTouch". Havent tested.  It could be modified pretty easily to behave like the example you posted above. The thing I don't like about that example is you can't easily select a range of 1 day.  Still working on it

**Comment by clauderic** [comment]
Hey @offsky, nice job. I played with your fork a little, it's still a little rough around the edges, but a lot better than I expected. Auto scrolling up/down is a really nice touch.

I have to say it's a little quirky to have to drag select on desktop though, I feel like it would be more natural if it was on hover once you select your start date. There's also the challenge of figuring out how this should be rendered in the header

**Comment by offsky** [comment]
Not yet. Its very much a work in progress. I just checked in some changes to my fork that will allow it to work on touch devices and handles range sections where (star>end). I also made the CSS a little nicer and got the before/on/after events firing appropriately.

If you prefer [click hover click] instead of what I have done [click drag release] it would be pretty easy to support this. Its essentially what I fall back on for touch devices. 

More work needs to be done.

**Comment by offsky** [comment]
Ive gotten my branch pretty close.  It now works with `disabledDates/disableDays` and the header displays the range appropriately.  Can you please take a look?  

You'll need to set `allowRanges=true` on the component since I have range selection disabled by default to preserve backwards compatibility with your component.  I have the behavior set to [click drag release] right now. If you want to see how it works with [click hover click] you can use it on a touch device or make this change: /src/index.js:line34: `touchBehavior: true,`

**Comment by olslash** [comment]
Super good, thanks for working on this @offsky. I have a usecase in mind for it at work already.

For the record, i'm +1 on using the touch behavior by default, so a prop for that would be nice.

A couple bugs i see: 
* When loading the `npm start` page, the default selection is strange (screenshot below).
* The "Today ^" link doesn't seem to work anymore

![image](https://cloud.githubusercontent.com/assets/693493/16592808/444d7a6e-4297-11e6-920a-1374cf47931f.png)

**Comment by offsky** [comment]
I have fixed the bug with the initially set date range showing that odd behavior if they are set backwards (start>end).

I also added a prop (rangeSelectWithDrag default true) for the drag vs touch behavior of selecting the range.

https://github.com/Toodledo/react-infinite-calendar/commit/16436fd4302a93446cf6133b3bb8a7df2544ad6c

**Comment by thisconnect** [comment]
click hover click should be default IMO

**Comment by olslash** [comment]
Hey @clauderic, I'd love to see this on master -- what's the path towards getting it merged look like?

**Comment by clauderic** [comment]
@olslash I haven't had the chance to take a look at @offsky's latest changes yet but from what I last saw I think most of the work for this to be merged back into master would be related to tweaking the look & feel, needs a bit more spit & polish. I also strongly believe the default behaviour on desktop should be `click–hover–click`

**Comment by offsky** [comment]
My latest changes resolve all the issues that I am aware of, so please check it out.  The click–hover–click thing is a single boolean in the default props, so thats easy to change either direction. Do you want me to submit a pull request?

**Comment by clauderic** [comment]
@offsky Absolutely, create the PR and we can discuss there :)

**Comment by offsky** [comment]
I have created the pull request, but it is failing the CI.  I have looked at the results and I can't figure out why. All the tests pass on my machine. Can someone please try running the tests for me and let me know if they get different results?

**Comment by clauderic** [comment]
Hey all, just published `react-infinite-calendar` Version 2.0, which comes with date-range selection out of the box  🎉

Check out the updated demo site to play with it: http://clauderic.github.io/react-infinite-calendar/#/enhance-default-functionality/range-selection

*Disclaimer: It's still experimental and there are a few bugs to iron out on mobile, but PRs are welcome to make it better!*

Here's the final look & feel I settled on:

<img width="451" alt="screen shot 2017-02-24 at 10 00 26 pm" src="https://cloud.githubusercontent.com/assets/1416436/23327587/b1c4a9ca-fadc-11e6-9be4-bd98bc3f4447.png">

Usage is as follows:

```jsx
import React from 'react';
import {render} from 'react-dom';
import InfiniteCalendar, {
  Calendar,
  withRange,
} from 'react-infinite-calendar';
import 'react-infinite-calendar/styles.css';

render(
  <InfiniteCalendar
    Component={withRange(Calendar)}
    selected={{
      start: new Date(2017, 1, 10),
      end: new Date(2017, 1, 18),
    }}
  />,
  document.querySelector('#root')
);
```

If you're curious about the implementation, check out https://github.com/clauderic/react-infinite-calendar/blob/master/src/Calendar/withRange.js

For more details, check out #33

**Comment by bvaughn** [comment]
That UI looks super slick!

**Comment by capaj** [comment]
@clauderic this is awesome. Much better for selecting short ranges than two separate inputs. Love it! I'll try to put this into production at our current company. Our datepickers suck and need a rewrite/replacement anyway!

**Comment by daiky00** [comment]
Hi @olslash how did you get the red pill with the number 5 in your calendar? look at the pic below
![image](https://user-images.githubusercontent.com/15005162/47588446-cb27bb80-d92b-11e8-93bd-e66120f01793.png)
