### ISSUE TITLE
Click on today helper not work.

### ISSUE THREAD

**Issue by blackChef** [clauderic/react-infinite-calendar#40]
import React from 'react';
    import ReactDOM from 'react-dom';
    import InfiniteCalendar from 'react-infinite-calendar';
    import 'react-infinite-calendar/styles.css';
    
    ReactDOM.render(
      <InfiniteCalendar />,
      document.querySelector('.appContainer')
    );

This is my code, nothing special. I traced down the source code, found out that I got undefined scrollEl every time. Please help.
![20160803111103](https://cloud.githubusercontent.com/assets/5157935/17352680/3a962288-596b-11e6-9c01-9476df14e91b.png)

**Comment by clauderic** [comment]
Can you provide more details about your setup? What version of react are you using? Is this something you're able to replicate in a jsfiddle? https://jsfiddle.net/clauderic/4rhn03do/

**Comment by blackChef** [comment]
There's really no more details about it. You demo works fine for me, but I don't know why it doesn't work when I use it in code. 
I create a repo [here](https://github.com/blackChef/react-infinite-calendar-test/). You can help me check it.

**Comment by clauderic** [comment]
Thanks for sharing the repo. Allowed me to pinpoint the issue. Had to do with a change introduced in react-virtualized as of 7.15.1. I'll be releasing a fix for this to npm shortly
