### ISSUE TITLE
Error: addComponentAsRefTo(...)

### ISSUE THREAD

**Issue by tommedema** [clauderic/react-infinite-calendar#41]
I'm trying to use `react-infinite-calendar` in an existing react app. These are my steps:

1. because our webpack config excludes `node_modules`, webpack wouldn't run the loaders needed by react-infinite-calendar, therefore I created 2 new loaders in our webpack config:

            {
                test: /\.jsx?$/,
                loaders: ['babel'],
                include: /react-infinite-calendar/
            },
            {
                test: /(\.scss|\.css)$/,
                loaders: ['style', 'css?sourceMap&modules&importLoaders=1&localIdentName=Cal__[name]__[local]!postcss!sass?sourceMap'],
                include: /react-infinite-calendar/
            }

2. when I run the application i get the following error

```
invariant.js:38 Uncaught (in promise) Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).(…)
```

The calendar does not render successfully as a result of the exception:
<img width="400" alt="screen shot 2016-08-04 at 16 19 35" src="https://cloud.githubusercontent.com/assets/331833/17395115/48bb4830-5a5f-11e6-87a7-1db39a2b78ab.png">

**Comment by tommedema** [comment]
Shouldn't you define `react` as a `peerDependency` rather than a `dependency`?

**Comment by clauderic** [comment]
Hey @tommedema, regarding your css loader, all you need is style-loader and css-loader, something along the lines of:

```js
{
    test: /(\.css)$/,
    loaders: ['style', 'css'],
    include: /react-infinite-calendar/
}
```

As for the second issue, I just removed react from dependencies, inadvertently let it crawl back there without noticing.

You most likely have two versions of React installed. You can usually safeguard against this with something like this in webpack:

```js
resolve: {
    alias: {
        "react": __dirname + '/node_modules/react',
    }
}
```

**Comment by nickcan** [comment]
@clauderic our team has been using your package in our app for months now. We have some other logic that we have combined with it (time selection, data management, etc). Anyways, we have moved all this logic into our own private package in NPM, including your infinite calendar.

It builds fine, but when we render the component in our app, the same `addComponentAsRefTo` bug pops up in this issue. I have tried resolving "react" to the alias as you put above and it doesn't work. If I remove the infinite scroller, it renders without the error. This is happening with other 3rd party packages as well, not just this one. Seems to be some sort of peer dependency management issue with React possibly loading in multiple areas.

Have any insight on how to get around the issue? Ever run into it when building a package that uses a 3rd party component (which also needs React)?

**Comment by nickcan** [comment]
Also, as part of my investigation, I ended up refactoring our private package to take a calendar prop. Then in our app, I pass `InfiniteCalendar` as the prop. That works. Obviously not ideal or a solution my team and I are going to move forward with, but it helped me realize that including the project "higher up" worked. Thanks

**Comment by nickcan** [comment]
@clauderic Sorry for bothering. We were able to figure this out. We needed to add "React"  to an `externals` field in our Webpack config. We then found out that `npm link` breaks the external/peer dependency tree. So, the combo of `externals` and `npm install --save ../path/to/package` works.

Just wanted to let you know so you don't waste your time responding here. Thanks
