### ISSUE TITLE
Custom components/renderers as props

### ISSUE THREAD

**Issue by GregoryPotdevin** [clauderic/react-infinite-calendar#44]
I haven't checked out the code yet, so can't tell if it would be easy or not, but one thing I've done on other components is to be able to pass components or function renderers as props, like `< InfiniteCalendar header={<MyCustomCalendarHeader />} />`. This allows for much more sophisticated theming/customizations, displaying dates differently, having custom "cells" for days, etc.

If others are interested I can start working on it later this week and see how it could work.

**Comment by GregoryPotdevin** [comment]
Did a really quick test just to see, the way the code is organized makes it trivial to pass custom components/renderers as props.

Here are the changes needed to pass a custom Header : https://github.com/GregoryPotdevin/react-infinite-calendar/commit/e2558065c3e1e1c77667d77be8f5b6ff185fc985 (haven't added the tests or anything)

Using a custom header created by cloning the current one : 
```jsx 
<InfiniteCalendar header={AlternativeHeader}/>
```

![image](https://cloud.githubusercontent.com/assets/1522455/17755504/8ade1e92-64da-11e6-8542-f4d16de7eb7d.png)

It should be pretty straightforward to do the same thing for the `Day` component.

**Comment by clauderic** [comment]
Hey @GregoryPotdevin, there have been talks about this in #15, and it's definitely something I'd be interested in working on, but I'm hesitant to do so until I know for sure it wouldn't conflict with other planned features (such as date range selection #33), or at least would like to make sure we find a way to conciliate both of these features.

**Comment by twig** [comment]
Damn, that's the only thing I wanted which was missing from this awesome calendar component!

Gonna have to go with https://github.com/react-component/calendar instead.

**Comment by clauderic** [comment]
Hey guys, just shipped version `2.0.0`, which comes with the ability to enhance or replace the built-in components.

You can now pass a custom `DayComponent`, `HeaderComponent`, and `YearsComponent` prop.

Check out #73 for more details.

If you'd like to get a better sense of what that looks like in practice, check out https://github.com/clauderic/react-infinite-calendar/blob/master/src/Calendar/withMultipleDates.js or https://github.com/clauderic/react-infinite-calendar/blob/master/src/Calendar/withRange.js

**Comment by daiky00** [comment]
@clauderic I just found this how do you pass a ```DayComponent```? what attribute do I need to use?
