### ISSUE TITLE
add examples from clauderic.github.io to repo

### ISSUE THREAD

**Issue by netpoetica** [clauderic/react-infinite-calendar#47]
Do you also think it would be very helpful if there was an examples/ dir that contains the examples at http://clauderic.github.io/react-infinite-calendar/#/basic-settings/basic-configuration?_k=g8hyyp

This would allow developers working on this project to be able to run a local comparison side-by-side against expected behaviors from the given examples.

Ideally this would include a simple `npm run dev` or `npm start` command, with a simple server, that will run the examples dir.

**Comment by netpoetica** [comment]
Closing this as it is actually mostly covered already. Running `npm run build && npm start` will start a local server w/ an index you can develop against. I think this is good enough!

This was a case of not reading the package.json properly ;)

**Comment by clauderic** [comment]
Still, point taken. I might spend some time adding `react-storybook` when I get the chance 👍
