### ISSUE TITLE
invalid number of rows

### ISSUE THREAD

**Issue by marek-sed** [clauderic/react-infinite-calendar#5]
when
min=05.2016
minDate=05.31.2016
locale={{week: { dow: 1, doy: 4 }}}

first row of june overlaps first row of may

**Comment by clauderic** [comment]
That's not a valid format for min. Use min="05.01.2016" and it should work fine

**Comment by marek-sed** [comment]
sry for not precise input

this is the setup that causes the issue
`<InfiniteCalendar
       min={moment().startOf('month')}
       minDate={moment().startOf('day')}
       locale={{week: { dow: 0, doy: 4}}} />`

I fixed it here [commit](https://github.com/marek-sed/react-infinite-calendar/commit/c3c1068d6f0bf09a621d0ef1e8176c78167e8b77)

**Comment by clauderic** [comment]
Hmm. Interesting, in theory moment.week() should be locale aware. I'll check it out

**Comment by clauderic** [comment]
File this one in the `wtf` category. For some reason, Moment.js wasn't picking up that a custom locale was present when this function was being run on initial render. Force-feeding it the locale fixed it

**Comment by marek-sed** [comment]
Thx for the fix. 
Btw the calendar is awesome btw, beautifully made.
