### ISSUE TITLE
react-infinite-calendar still tries to load VirtualScroll from react-virtualized

### ISSUE THREAD

**Issue by mach1** [clauderic/react-infinite-calendar#51]
Altho I have
`"react-virtualized": "^8.0.11"`
`"react-infinite-calendar": "~1.2.0"`
Installed and 
`cat node_modules/react-infinite-calendar/package.json | grep version` > `"version": "1.2.0"`

react-infinite-calendar still tries to load `VirtualScroll` from `react-virtualized` instead of `List` introduced in version 8.

**Comment by clauderic** [comment]
Hrmm... Where? 🤔

**Comment by clauderic** [comment]
Nevermind. Build was borked. Just published `1.2.1` to npm. Sorry about that!

**Comment by mach1** [comment]
Thanks! 🎉
