### ISSUE TITLE
Bug in latest version - cant fire click events on last week days

### ISSUE THREAD

**Issue by Nedgeva** [clauderic/react-infinite-calendar#52]
Cannot click on gray date - last week's dates.
Happened to me when i updated from v1.1.18.

**Comment by ThomsCass** [comment]
same here :

I just update to the last version react-infinite-calendar": "^1.2.1" and I can't select date around the default date

<img width="427" alt="capture d ecran 2016-09-29 a 19 44 35" src="https://cloud.githubusercontent.com/assets/10784312/18968016/9ff4f76e-8687-11e6-8cab-48861e066d27.png">


for example here :

I can't select the 25, 26, 27, 28 and 30 of september all the rest is fine.

when I look into the html the li inside the row are not created.

any ideas ?

Thanks

**Comment by clauderic** [comment]
Ahhh. Sorry about that, 1.2.0 introduced a number of changes which caused a css rule to be ignored, which resulted in the zIndex glitches you both saw. Just published 1.2.2 to npm with a fix for this.

Thanks for reporting this!
