### ISSUE TITLE
Error when including the css

### ISSUE THREAD

**Issue by j-s-n** [clauderic/react-infinite-calendar#55]
In what circumstances is `import 'react-infinite-calendar/styles.css';` expected to work? I'm using browserify/babelify and I get an "Unexpected Token" error when trying to build - I don't think importing css files in js source files will work without some kind of transform, at least with browserify (and I haven't had any luck with the browserify-css transform). Any suggestions?

**Comment by clauderic** [comment]
Hey @j-s-n, you need to use the appropriate loader / transformer. In your case, you should simply look into using something like [browserify-css](https://github.com/cheton/browserify-css)
