### ISSUE TITLE
how to get the LocaleProcider?

### ISSUE THREAD

**Issue by RifeWang** [clauderic/react-infinite-calendar#56]
i want to change the English to Chinese or number like October to 10月 , and the header change to 2016-10-22 . How can i do ?

**Comment by clauderic** [comment]
You can use the `locale` prop to pass in a custom locale to `react-infinite-calendar`. Behind the scenes, it relies on [Moment.js](momentjs.com) for date parsing, so you can pass in all the params it supports, as well as a few custom ones specific to `react-infinite-calendar` (such as `todayLabel`, `headerFormat` and `blank`).

Here's an example I put together from looking at the [Moment.js locale for zh-cn](https://github.com/moment/moment/blob/develop/locale/zh-cn.js): 
<img width="414" alt="screen shot 2016-10-22 at 9 42 04 am" src="https://cloud.githubusercontent.com/assets/1416436/19619730/d54036e8-983b-11e6-8d6c-d9d626945752.png">

And here is the code:
https://jsfiddle.net/4rhn03do/23/

P.S. I don't speak Chinese so I'm not sure how accurate my example is 😅

**Comment by RifeWang** [comment]
@clauderic  thank you very much! it's very accurate.
