### ISSUE TITLE
have no response sometimes when i click and scroll

### ISSUE THREAD

**Issue by RifeWang** [clauderic/react-infinite-calendar#57]
it like a static picture sometimes and have no response when i click and scroll it. i just imported and rendered this component , maybe it's slow? and how to get the value of the onSelect event , i mean that i just wanna the date like 2016-10-23, not Wed Oct 26 2016 00:00:00 GMT+0800.

**Comment by clauderic** [comment]
Hey @RifeWang, not sure about the performance concerns you're speaking of. Perhaps you could take a video to illustrate?

Regarding the `onSelect` event, it returns a standard [JavaScript Date object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date), which you can then parse yourself back to `YYYY-MM-DD` (here's a [stackoverflow thread](http://stackoverflow.com/questions/3066586/get-string-in-yyyymmdd-format-from-js-date-object) on how).

Alternatively, you can use [Moment.js](http://momentjs.com), which makes it very simple to format dates:
 ```js
onSelect={(date) => 
    console.log(moment(date).format('YYYYMMDD'))
}
```

**Comment by RifeWang** [comment]
[issue.zip](https://github.com/clauderic/react-infinite-calendar/files/546436/issue.zip)
@clauderic

**Comment by RifeWang** [comment]
my here is too late ,good night, and discuss tomorrow

**Comment by RifeWang** [comment]
@clauderic i found the reason,it's my css problem,not this component.

**Comment by RifeWang** [comment]
my css influenced the component's focus
