### ISSUE TITLE
Server rendering?

### ISSUE THREAD

**Issue by brickyang** [clauderic/react-infinite-calendar#58]
I am building an univers app. I tried to use RIC but it seems that it doesn't work for server rendering? Or maybe I got wrong on something?

**Comment by clauderic** [comment]
Hey @brickyang, I haven't had to use this project in an SSR environment. Would you be interested in contributing a PR that implements this?

**Comment by brickyang** [comment]
I would like to try, but I can't make any promise. Because I haven't tried PR a project before. Not sure if I can do it right. Anyway, I will try my best.

**Comment by leian-ivey** [comment]
I had the same issue earlier and created the PR - https://github.com/clauderic/react-infinite-calendar/pull/98
