### ISSUE TITLE
The beginning and end of a month rendered in a strange way.

### ISSUE THREAD

**Issue by Stas-Buzunko** [clauderic/react-infinite-calendar#59]
Hi, have no idea why it happens, attached a few screenshots.
![image](https://cloud.githubusercontent.com/assets/12331100/20596069/b61c464a-b24d-11e6-8463-0cebddd20988.png)
![image](https://cloud.githubusercontent.com/assets/12331100/20596085/c1cf58c4-b24d-11e6-86a7-558b145d5fe7.png)
![image](https://cloud.githubusercontent.com/assets/12331100/20596102/ce5c73ec-b24d-11e6-8ceb-1649ce5ad83f.png)

Styles are imported, 
Usage:
```
<InfiniteCalendar afterSelect={(e) => this.updateDate(e)} selectedDate={false} disabledDates={bookedDates} minDate={moment().startOf('day')} />
```

Even when left <InfiniteCalendar /> still the same issue.
Your calendar looks good and I'd like to use it in my project, what could be the issue?

**Comment by clauderic** [comment]
Hey @Stas-Buzunko,

Could it be that you have `text-align: center;` somewhere? If you want to center the header, try applying more specific css

**Comment by Stas-Buzunko** [comment]
Thanks, I will have a look and reply :)

**Comment by Stas-Buzunko** [comment]
Yes! You were right, thank you!
