### ISSUE TITLE
Bug: Uncaught TypeError: Cannot read property 'isSame' of null

### ISSUE THREAD

**Issue by abury** [clauderic/react-infinite-calendar#63]
Hey @clauderic 

First of all, thanks so much for a great component. It's amazing. Not sure if this is a bug or intended but I get the following exception when rendering react-infinite-calendar with  a minimum date and null selectedDate I get the following error:

``TypeError: Cannot read property 'isSame' of null``

I've created a fork at: https://jsfiddle.net/abury/o80kxzha/

It's referring to [line 119 of index.js](https://github.com/clauderic/react-infinite-calendar/blob/master/src/index.js#L119). It looks like we just need to check for the existence of selectedDate in the preceding if. Let me know if its intended or not and I'll create a fork with a fix.

Thanks!

Aron

**Comment by clauderic** [comment]
Hey @abury, thanks for the detailed report ❤️ 

I tried replicating the issue you speak of, but to no avail. https://jsfiddle.net/o80kxzha/1/

I think perhaps you sent the link to the wrong fiddle? 😅 

Either way, this is most certainly not intended behaviour, so absolutely a PR would be most welcome!

**Comment by abury** [comment]
@clauderic hmm, it doesn't seem to be happening for me in the fiddle either (I'm new to the JS world so still learning how these things work, does JSFiddle show errors in a console anywhere?)

It's definitely occurring consistently in my project, I might spend some more time trying to look into it today. 👍

**Comment by clauderic** [comment]
Hey @abury, FYI, I just shipped version `2.0.0`, which replaces `moment.js` in favor of `date-fns`. This should no longer be an issue, though let me know if you run into any other issues
