### ISSUE TITLE
[Firefox] Vulnerable to DST changes

### ISSUE THREAD

**Issue by syko** [clauderic/react-infinite-calendar#66]
Basically `moment(...).range('year').toArray('months')` is giving us 13 months here: https://github.com/clauderic/react-infinite-calendar/blob/master/src/utils.js#L34

This is because there is a DST change at midnight and behind the scenes momentjs is just adding hours to get the next date but is failing miserably.

This is not a problem with this calendar per se but an issue with the javascript's Date object which bubbles up through momentjs and we end up with 2 Marches in 1982 `Tallinn/Helsinki` time zone. 

Issue in momentjs repo: https://github.com/moment/moment/issues/1864

I'm creating an issue here too because the root cause can be seen as using datetime objects to represent dates and it sounds unlikely that firefox/momentjs will get around to fixing this any time soon.

The result of this bug is that some years have 13 months which is throwing off all `scrollTop` calculations big-time. (and we have 2 of some months which is weird too)

**Comment by clauderic** [comment]
Hey @syko, just shipped version `2.0.0`, which replaces `moment.js` and `moment-range` in favor of `date-fns`. This should no longer be an issue forward, though let me know if you're still seeing this issue.
