### ISSUE TITLE
[Firefox] cannot display SVG chevron on "today" bar when theme color is hex value

### ISSUE THREAD

**Issue by offsky** [clauderic/react-infinite-calendar#67]
![screen shot 2017-01-11 at 8 09 52 am](https://cloud.githubusercontent.com/assets/1110926/21856083/82ff89f4-d7d5-11e6-97d3-82e0ca6316e6.png)

**Comment by clauderic** [comment]
Hey @offsky, thanks for flagging this! I believe it's because Firefox doesn't support using `data:image/svg` in an image src. Should be a fairly simple fix, just need to inline the svg instead.

Would you care to submit a PR? If not, I should get around to it within the next couple of days

**Comment by offsky** [comment]
I dug into it. It does seem that Firefox is buggy.  If you replace the fill parameter of the inline svg with "red" then it works. "rgb(255,0,0)" also works.  As soon as you change it to a hex value like "#ff0000" it fails.  So maybe the # character is buggy in inline svgs on firefox? Not sure.  

I worked around the bug by specifying my theme color for the chevron as rgb() instead of hex. If you want to allow hex colors, then inline svg is probably the way to go.  I'll leave that for you since I have a decent workaround and don't have time to do another PR right now. Sorry.

**Comment by clauderic** [comment]
No worries man, thanks for looking into it and sharing your findings

**Comment by clauderic** [comment]
Fixed in `2.0.0`, decided to use inline-svg instead https://github.com/clauderic/react-infinite-calendar/blob/master/src/Today/index.js#L47
