### ISSUE TITLE
Improving performance of initial render

### ISSUE THREAD

**Issue by offsky** [clauderic/react-infinite-calendar#68]
I am looking into improving performance of the initial render, especially on mobile browsers.  In my initial investigation, I noticed that when the calendar loads, it initially draws the entire calendar from 1980 and then immediately redraws the entire thing with the proper dates. This is an easy 2x perf boost if we can avoid this.

I am happy to take a stab at this, but I would like some advice or pointer in the right direction. Here is what I see:

1) List component is rendered once with the wrong 1980 dates stored in this.props.months
2) List.render() is never called again
3) Somehow List.renderMonth() is called a bunch of times with the wrong data and then a bunch more times with the correct data. Im not sure how the children are rerendering when the parent isnt. Some magic with VirtualScroll?
4) I can't see where the "months" array is updated.

Thanks!

**Comment by clauderic** [comment]
Hey @offsky, I actually have a (private) fork of this that focuses heavily on perf gains by replacing `Moment.js` with `date-fns` and implements a lot of the perf improvements you mentioned to improve initial render.

It's not quite ready for prime-time yet, but I'd be happy to share the implementation with you to get some of your feedback.

**Comment by offsky** [comment]
yes, please

**Comment by thisconnect** [comment]
Looking forward to `react-infinite-calendar` using `date-fns`

**Comment by Youmoo** [comment]
+1. Looking forward to `react-infinite-calendar` using `date-fns` , too.

**Comment by chadoh** [comment]
Totes, initial render time on mobile makes this thing unusable for me right now. And I'd love to not have to import Moment! Didn't know about `date-fns`, but 💯 

Can I help make this happen somehow? I love the promise of `react-infinite-calendar`, but can't use it until this gets straightened out.

**Comment by clauderic** [comment]
Hey guys, just wanted to let you know that the release of version 2.0 is just around the corner. Version 2.0 focuses on initial render performance and drops Moment.js in favor of `date-fns`.

If you'd like to test it out ahead of its release, run `npm install react-infinite-calendar@next` locally. Would love some feedback!

For more details, refer to #73

**Comment by clauderic** [comment]
FYI, Just shipped version `2.0.0` with `date-fns`, and lot's of other cool stuff. You should see much faster initial render performance with this version, though I'm sure there are still perf improvements to be made. 

PRs are welcome if you find anything that can be improved!
