### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by arackaf** [clauderic/react-infinite-calendar#71]
After a fresh clone, `npm install`, `npm build` throws this error.

On both Windows 10, and also Mac.

Are there any global npm installs I should have? 

> > npm run clean:es6 && cross-env BABEL_ENV=es6 BABEL_DISABLE_CACHE=1 babel src --out-dir dist/es6 --ignore *.test.js

> react-infinite-calendar@1.2.2 clean:es6 c:\GIT\react-infinite-calendar-original
> rimraf dist/es6

node_modules\nan
resolve failed:  { [Error: Cannot find module 'caniuse-db'] code: 'MODULE_NOT_FOUND' } caniuse-db
resolve failed:  { [Error: Cannot find module 'babel-runtime'] code: 'MODULE_NOT_FOUND' } babel-runtime
resolve failed:  { [Error: Cannot find module 'webpack-core'] code: 'MODULE_NOT_FOUND' } webpack-core
Error: src/Day/index.js: Module 'c:\GIT\react-infinite-calendar-original\babel.preprocess.sass.js' does not exist or is not a function.
    at c:\GIT\react-infinite-calendar-original\node_modules\babel-plugin-css-modules-transform\build\index.js:116:35
    at Array.forEach (native)
    at PluginPass.Program (c:\GIT\react-infinite-calendar-original\node_modules\babel-plugin-css-modules-transform\build\index.js:77:32)
    at newFn (c:\GIT\react-infinite-calendar-original\node_modules\babel-traverse\lib\visitors.js:276:21)
    at NodePath._call (c:\GIT\react-infinite-calendar-original\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (c:\GIT\react-infinite-calendar-original\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (c:\GIT\react-infinite-calendar-original\node_modules\babel-traverse\lib\path\context.js:105:12)
    at TraversalContext.visitQueue (c:\GIT\react-infinite-calendar-original\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (c:\GIT\react-infinite-calendar-original\node_modules\babel-traverse\lib\context.js:108:19)
    at TraversalContext.visit (c:\GIT\react-infinite-calendar-original\node_modules\babel-traverse\lib\context.js:192:19)
    at Function.traverse.node (c:\GIT\react-infinite-calendar-original\node_modules\babel-traverse\lib\index.js:114:17)
    at traverse (c:\GIT\react-infinite-calendar-original\node_modules\babel-traverse\lib\index.js:79:12)
    at File.transform (c:\GIT\react-infinite-calendar-original\node_modules\babel-core\lib\transformation\file\index.js:558:35)
    at c:\GIT\react-infinite-calendar-original\node_modules\babel-core\lib\transformation\pipeline.js:50:19
    at File.wrap (c:\GIT\react-infinite-calendar-original\node_modules\babel-core\lib\transformation\file\index.js:574:16)
    at Pipeline.transform (c:\GIT\react-infinite-calendar-original\node_modules\babel-core\lib\transformation\pipeline.js:47:17)
    at transform (c:\GIT\react-infinite-calendar-original\node_modules\babel-cli\lib\babel\util.js:50:22)
    at Object.compile (c:\GIT\react-infinite-calendar-original\node_modules\babel-cli\lib\babel\util.js:59:12)
    at write (c:\GIT\react-infinite-calendar-original\node_modules\babel-cli\lib\babel\dir.js:21:21)
    at handleFile (c:\GIT\react-infinite-calendar-original\node_modules\babel-cli\lib\babel\dir.js:43:7)
    at c:\GIT\react-infinite-calendar-original\node_modules\babel-cli\lib\babel\dir.js:62:11
    at Array.forEach (native)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:es6"
npm ERR! node v4.4.5
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! react-infinite-calendar@1.2.2 build:es6: `npm run clean:es6 && cross-env BABEL_ENV=es6 BABEL_DISABLE_CACHE=1 babel src --out-dir dist/es6 --ignore *.test.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-infinite-calendar@1.2.2 build:es6 script 'npm run clean:es6 && cross-env BABEL_ENV=es6 BABEL_DISABLE_CACHE=1 babel src --out-dir dist/es6 --ignore *.test.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-infinite-calendar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean:es6 && cross-env BABEL_ENV=es6 BABEL_DISABLE_CACHE=1 babel src --out-dir dist/es6 --ignore *.test.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-infinite-calendar
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-infinite-calendar
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\GIT\react-infinite-calendar-original\npm-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v4.4.5
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! react-infinite-calendar@1.2.2 build: `npm run build:commonjs && npm run build:es6 && npm run build:umd`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-infinite-calendar@1.2.2 build script 'npm run build:commonjs && npm run build:es6 && npm run build:umd'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-infinite-calendar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:commonjs && npm run build:es6 && npm run build:umd
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-infinite-calendar
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-infinite-calendar
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\GIT\react-infinite-calendar-original\npm-debug.log

**Comment by clauderic** [comment]
Hey @arackaf,

Sorry about that. I'm actually currently working on version 2.0, which should solve all of these issues.

Version 2.0 also removes of `Moment.js` in favor of `date-fns` and also has a lot of other performance improvements, especially in terms of initial render. I'll post more details soon.

In the meantime though, if you'd like to give it a spin, check out https://github.com/clauderic/react-infinite-calendar/tree/version-2

**Comment by arackaf** [comment]
@clauderic - awesome, thanks so much.  I'm curious - does the version-2 support multiple date selection?  Truth be told, that's the main thing we're looking for - we wound up finding a fork of your original one that added that, which is how we found out about the broken build :)   (is broken both in the fork and original - don't worry, I didn't open a case for a problem in a fork)

**Comment by clauderic** [comment]
@arackaf multiple date selection won't be supported out of the box when 2.0 comes out, but it is something I plan on working on in the near future. If you're planning on forking the original and working on that, I strongly advise you wait until version 2.0 is released (should be a matter of days at this point!)

If you'd like to test it out, run `npm install react-infinite-calendar@next` locally. Would love some feedback! Check out https://github.com/clauderic/react-infinite-calendar/pull/73 for more details and the full list of changes

**Comment by dpratt71** [comment]
@clauderic I work with @arackaf and his questions have actually been on my behalf. I've extended v1 of your excellent component to support a kind of multi-date selection. What I have actually done is defined a `MarkedDates` property on the component that is implemented in a very similar fashion to the existing `DisabledDates` property.

I've cloned the `version-2` branch of the component in the hopes that I could implement the `MarkedDates` property for it and send you a PR. Unfortunately, I've struggled with getting the v2 component integrated into our project.

A minor issue was that it seems like stylesheet minification is not yet implemented? A bigger issue is that I guess I don't understand how `npm.umd.externals` in `nwb.config.js` is supposed to work. For one thing, I would have expected to see the other peer dependencies mentioned there, but it's just React. For another, if we have things registered differently in our project, it's not clear to me how to reconcile that.

Does the `MarkedDates` property sound like a feature you would want to add? If I sent you a PR for v1 of the component, would you consider translating it to v2 of the component?

**Comment by clauderic** [comment]
Hey @dpratt71, regarding the umd configuration not also treating other peerDependencies as externals, that's simply an oversight on my part 😅 

I'm actually currently working on integrating version 2 with [recompose](https://github.com/acdlite/recompose), which should make it fairly simple to add opt-in layers of functionality like date-range selection and multiple selected dates by enhancing the original components and state via HOCs. 

Here's a basic example of what it's going to look like in practice. Here, I've implemented the logic for displaying and selecting a single date:

<img width="752" alt="screen shot 2017-02-20 at 4 48 29 pm" src="https://cloud.githubusercontent.com/assets/1416436/23142932/7edd7152-f78c-11e6-8895-49f4cb9b90f1.png">

For this reason, this isn't actually something I'd consider merging at this stage.

**Comment by clauderic** [comment]
Out of curiosity, how are you rendering the header in your fork? Or did you choose to not display the header?

I'm trying to find a way to elegantly display the multiple date selection in the header

**Comment by dpratt71** [comment]
@clauderic [my changes](https://github.com/clauderic/react-infinite-calendar/compare/version-2...dpratt71:version-2) leave `selectedDate` and its behavior/appearance intact. I thought I wanted full-on multi-select at first, but then I realized that I just needed to show the user which days they had previously selected. Hence the `markedDates` property.

**Comment by clauderic** [comment]
FYI, I just published version `2.0.0`, which should fix the build issues you were facing and comes with multiple date selection out of the box. Here's what it looks like:

<img width="438" alt="screen shot 2017-02-24 at 10 15 55 pm" src="https://cloud.githubusercontent.com/assets/1416436/23327715/14e846ea-fadf-11e6-8e62-2d317711751f.png">

It's still experimental at this point, but if you're curious to try it out, check out the update demo site:
http://clauderic.github.io/react-infinite-calendar/#/enhance-default-functionality/multiple-date-selection?_k=16lp8h

**Comment by arackaf** [comment]
@clauderic 4 days ago

> @arackaf multiple date selection won't be supported out of the box when 2.0 comes out

@clauderic 30 seconds ago

> FYI, I just published version 2.0.0, which should fix the build issues you were facing and comes with multiple date selection out of the box.

Do you guys talk to each other???  :P 

No but seriously, thank you SO much for all your hard work - you produce amazing things for the OSS community.

**Comment by clauderic** [comment]
Hahaha, I changed my mind when I found out about [recompose](https://github.com/acdlite/recompose) 😅 

Thanks for the kind words buddy, means alot ❤️
