### ISSUE TITLE
Improve render performance

### ISSUE THREAD

**Issue by offsky** [clauderic/react-infinite-calendar#80]
Ive noticed two cases where render performance could be improved.

1) When the calendar loads, it initially draws the entire calendar from 1980 and then immediately redraws the entire thing with the proper dates. This is an easy 2x perf boost if we can avoid this.

2) When you are using the withRange() HOC, the entire calendar re-renders on every mouse movement. It should be possible to only update the header and the dates that have changed.

I'll update this issue if I find anything else.

**Comment by clauderic** [comment]
Regarding your first point, that was an issue related to [react-tiny-virtual-list](https://github.com/clauderic/react-tiny-virtual-list). Just pushed 2.1.3 which should address this.

Regarding the second point, all components use PureComponent and will only update if their props change.

**Comment by offsky** [comment]
For item 2, I put a console.log inside the render method of day/index.js and on every mouse movement it spewed out a hundred messages. Maybe you could try this and see if it does the same for you. Ill double check tomorrow.

**Comment by clauderic** [comment]
Ah, it could be an issue specific to range selection, since the selected state for range selection is an object

**Comment by offsky** [comment]
I can confirm that this performance problem exists only when doing a range selection and only when a selection is in progress.

**Comment by lap123** [comment]
I think the problem is in withRange.js:60
The functions onClick and onMouseOver are allocated on every component update, therefore triggering a re-render.

**Comment by clauderic** [comment]
Yeah, @lap123 is right. Based on the current implementation, I'm not sure there's a way around it, but PRs are most welcome if any of you want to take a stab at it. Going to close out this issue since it isn't something that's actionable at the moment and I don't have the bandwidth to work on it myself.

**Comment by andresberrios** [comment]
I'm having this issue, but it doesn't seem to have performance issues when I use it in the demo: http://clauderic.github.io/react-infinite-calendar/#/enhance-default-functionality/range-selection?_k=lq88j9
What could be the difference?
