### ISSUE TITLE
Range selection misaligned when crossing months in Chrome

### ISSUE THREAD

**Issue by MrSauceman** [clauderic/react-infinite-calendar#83]
The background of the selection range is misaligned when crossing through two months in Chrome.  See attached image.

![calendar](https://cloud.githubusercontent.com/assets/18271688/23587975/dc3d06e0-0183-11e7-97e6-6c6c67346fa9.png)

I was able to fix this by removing `top: 1px;` (line 20) and `margin-top: -1px;` (line 22) from Month.scss under the `row:first-child li` selector.  I tested this in Chrome and IE and it is working, but I am not sure if this breaks anything else within the calendar.

**Comment by clauderic** [comment]
Good catch! Fixed in `2.1.5`, thanks for reporting this 😄
