### ISSUE TITLE
Clicking year in range calendar not working

### ISSUE THREAD

**Issue by MrSauceman** [clauderic/react-infinite-calendar#84]
Getting `Cannot read property 'getFullYear' of null` when clicking on either the start year or end year of the range calendar.

**Comment by clauderic** [comment]
I believe this is no longer an issue, or at least not one I'm able to reproduce

**Comment by MrSauceman** [comment]
This is still happening for me when clicking on the year in the range calendar.  The error is a little different now, though:

````
Uncaught TypeError: selected.getFullYear is not a function
    at Years.render
````

**Comment by blackdynamo** [comment]
For anyone experiencing this issue, make sure you initialize the date you give the calendar with a date object not just a string date.
