### ISSUE TITLE
Range calendar date incorrect when no date is selected

### ISSUE THREAD

**Issue by MrSauceman** [clauderic/react-infinite-calendar#85]
The range calendar shows `1969 Wed, Dec 31st` when no date is selected, instead of `Select a date...` like the regular calendar. Setting `selected={{ start: null, end: null }}` should reproduce this.

**Comment by clauderic** [comment]
Fixed by 7ccacd2, will go out in the next minor release.

**Comment by MrSauceman** [comment]
This did not fix the issue for me.  Still seeing ````1969 Wed, Dec 31st```` when no date is selected in the range calendar.

**Comment by cfristofer** [comment]
To fix the issue to the next : 

const today = new Date();
const  Dateclass = {
  start : new Date(),
  end :  today.setDate(today.getDate()+1)
};
render(
  <infiniteCalendar
    Component={withRange(Calendar)}
    width={Math.min(window.innerWidth, 400)}
    selected={Dateclass}
  
**if you want to avoid 1969 Wed, Dec 31st just send Dateclass  null and that's all.**
