### ISSUE TITLE
Hard to decide if I should star this repo!

### ISSUE THREAD

**Issue by rankun203** [clauderic/react-infinite-calendar#9]
<img width=110 src='https://cloud.githubusercontent.com/assets/2988555/15798930/702f734e-2a7d-11e6-9a23-215adb5eff9e.png'>

As you can see, there is 666 stars, which means, some way a good number. Maybe I should just leave it and add as a bookmark.

**Comment by clauderic** [comment]
Too late now... I suppose you'll just have to wait for `777` now ;p
