### ISSUE TITLE
Months are overlapping

### ISSUE THREAD

**Issue by lucasaid** [clauderic/react-infinite-calendar#97]
From the demo:
![image](https://cloud.githubusercontent.com/assets/1774266/24491017/046080f6-1571-11e7-8148-b8ccbba62a08.png)

The last week of July 2017 and first week of August 2017 are overlapping.

**Comment by clauderic** [comment]
Hey @lucasaid, I'm unable to replicate this. Are you seeing this in the live demo, or on your local machine?

Either way, can you share some more details about your browser, computer, timezone, etc?

**Comment by lucasaid** [comment]
Sorry should have included that stuff, this is both on the live demo and on local

On a Mac Sierra 10.12.3
Chrome 57.0.2987.98
Firefox 52.0
Safari 10.0.3
Android Chrome 57.0.2987.132

Seems to be across all browsers current timezone is UTC/GMT +10 hours Melbourne AEDT
